import { Mail } from "lucide-react";
import { PortalLayout } from "@/components/PortalLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { clientPortalNavItems } from "@/lib/clientPortalNav";
import { emptyStateCopy, momoCpV1Seed, statusTone } from "@/domain/momoCpV1/momoClientPortalSeed";
export default function ClientMessages() { return <PortalLayout items={clientPortalNavItems} portalName="Client Portal"><PageHeader title="Messages" description="Simple guidance from Veroxa will appear here when something needs your attention." testId="header-client-messages" /><section className="grid gap-4 lg:grid-cols-[1fr_0.9fr]"><Card data-testid="messages-from-veroxa"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Mail className="h-4 w-4 text-primary" />Messages from Veroxa</CardTitle></CardHeader><CardContent className="space-y-3">{momoCpV1Seed.messages.fromVeroxa.length ? momoCpV1Seed.messages.fromVeroxa.map(({subject, status}) => <div key={subject} className="rounded-lg border border-border/70 p-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium">{subject}</p><StatusBadge tone={statusTone(status)}>{status}</StatusBadge></div></div>) : <div className="rounded-lg border border-border/70 p-3 text-sm"><p className="font-medium">{emptyStateCopy.nothingNeeded}</p><p className="mt-1 text-muted-foreground">{emptyStateCopy.messages}</p></div>}</CardContent></Card><Card data-testid="how-to-contact-veroxa"><CardHeader><CardTitle className="text-sm">How to Contact Veroxa</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>Message sending inside the portal is not connected yet. For now, please contact Veroxa directly. This page will later show messages and replies inside the portal.</p><Button variant="outline" asChild><a href="mailto:faraz@veroxa.app">Contact Veroxa</a></Button></CardContent></Card></section></PortalLayout>; }
