import { HelpCircle, MessageSquare, ShieldCheck } from "lucide-react";
import { PortalLayout } from "@/components/PortalLayout";
import { RealPortalReviewNotice, SafePortalEmptyCard } from "@/components/RealPortalSafeStates";
import { PageHeader } from "@/components/common/PageHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { clientPortalNavItems } from "@/lib/clientPortalNav";
import { useClientSaasPortalState } from "@/hooks/useClientSaasPortalState";
import { getClientSafeEmptyStateForPage } from "@/domain/saas/clientPortalState";

export default function ClientRequests() {
  const { pageState, requestSummary } = useClientSaasPortalState();
  const grouped = pageState.clientRequests.reduce<Record<string, typeof pageState.clientRequests>>((acc, request) => { (acc[request.status] ??= []).push(request); return acc; }, {});
  return <PortalLayout items={clientPortalNavItems} portalName="Client Portal"><RealPortalReviewNotice /><PageHeader title="Requests" description="Ask Veroxa to review media direction, menu links, best-seller visibility, posting preferences, or report clarification." testId="header-client-requests" />
    {!pageState.isDemoData && !pageState.canShowRealData ? <SafePortalEmptyCard title="Requests in setup" body={getClientSafeEmptyStateForPage("requests", pageState)} /> : null}
    <div className="sr-only">Received In Review Handled Waiting for you</div><section className="grid gap-4 md:grid-cols-4 mb-4"><Metric label="Total" value={requestSummary.total} /><Metric label="In review" value={requestSummary.open} /><Metric label="Needs your input" value={requestSummary.needsClientConfirmation} /><Metric label="Resolved" value={requestSummary.resolved} /></section>
    <section className="grid gap-4 lg:grid-cols-[1.15fr_0.85fr]"><Card><CardHeader><CardTitle className="text-sm flex items-center gap-2"><MessageSquare className="h-4 w-4 text-primary" />Request status</CardTitle></CardHeader><CardContent className="space-y-4">{Object.entries(grouped).length > 0 ? Object.entries(grouped).map(([status, requests]) => <div key={status}><p className="mb-2 text-xs uppercase tracking-wide text-muted-foreground">{status.replaceAll("_", " ")}</p><div className="space-y-2">{requests.map((request) => <div key={request.id} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">{request.message}</p><p className="mt-1 text-xs text-muted-foreground">{request.clientVisibleStatus}</p></div>)}</div></div>) : <p className="text-sm text-muted-foreground">No live request workflow is connected yet.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-sm flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-primary" />Request boundaries</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground"><div><p className="font-medium text-foreground">What Veroxa can help with</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Use this photo next</li><li>Update menu link visibility</li><li>Highlight a best seller</li><li>Ask about posting preference</li><li>Request report clarification</li><li>Ask Veroxa to review media direction</li></ul></div><div><p className="font-medium text-foreground">What the restaurant still handles</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Guest conversations</li><li>Sensitive guest follow-up and payment/order support</li><li>Social inboxes and urgent guest messages</li></ul></div><p className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-xs">{requestSummary.nextAction}</p></CardContent></Card></section></PortalLayout>;
}
function Metric({ label, value }: { label: string; value: number }) { return <Card><CardContent className="p-4"><HelpCircle className="mb-2 h-4 w-4 text-primary" /><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></CardContent></Card>; }
