import { BarChart3, CalendarCheck, CheckCircle2, Info } from "lucide-react";
import { PortalLayout } from "@/components/PortalLayout";
import { RealPortalReviewNotice } from "@/components/RealPortalSafeStates";
import { PageHeader } from "@/components/common/PageHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { clientPortalNavItems } from "@/lib/clientPortalNav";
import { useClientSaasPortalState } from "@/hooks/useClientSaasPortalState";
import { buildMonthlyReportFromClientSummary } from "@/domain/monthlyReports";
import { momoCpV1Seed } from "@/domain/momoCpV1/momoClientPortalSeed";
export default function ClientReports() { const { reportSummaries, pageState } = useClientSaasPortalState(); const loadedMonthlyReport = reportSummaries.find((summary) => summary.reportType === "monthly"); const builtMonthlyReport = loadedMonthlyReport ? buildMonthlyReportFromClientSummary(loadedMonthlyReport, pageState.restaurant?.name ?? "Momo’s House") : null; const handled = builtMonthlyReport?.whatVeroxaHandled ?? momoCpV1Seed.reports.monthlyHandled; return <PortalLayout items={clientPortalNavItems} portalName="Client Portal"><RealPortalReviewNotice /><PageHeader title="Reports" description="Weekly Updates and Monthly Reports live together here so you can see what happened, what is planned, and what Veroxa needs next." testId="header-client-reports" /><Card className="mb-4"><CardHeader><CardTitle className="text-sm">Weekly Updates</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">What happened this week, what is planned next week, and what Veroxa needs from you.</CardContent></Card><section className="grid gap-4 lg:grid-cols-3"><ReportSection icon={CalendarCheck} title="What was done this week" items={momoCpV1Seed.reports.weeklyDone} /><ReportSection icon={CalendarCheck} title="What is next week’s plan" items={momoCpV1Seed.reports.weeklyNext} /><ReportSection icon={Info} title="What Veroxa needs from you" items={momoCpV1Seed.reports.weeklyNeeds} /></section><Card className="my-4"><CardHeader><CardTitle className="text-sm">Monthly Reports</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Owner-safe monthly report structure: are people able to find us, what work was prepared, what needs attention, and what is next?</CardContent></Card><ReportSection icon={CheckCircle2} title="What Veroxa handled" items={handled} /><Card className="my-4 border-primary/20 bg-primary/5" data-testid="monthly-reach-actions"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><BarChart3 className="h-4 w-4 text-primary" />Reach & Customer Actions</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Reach/action signals: Google and Meta performance data will appear after Veroxa has access and enough activity to report honestly. No live metrics, rankings claims, orders, profit, or ROI claims, or attribution math are shown.</CardContent></Card><section className="grid gap-4 lg:grid-cols-3"><ReportSection icon={CheckCircle2} title="What Worked / What Didn’t Work" items={["Worked: " + momoCpV1Seed.reports.worked.join(", "), "Didn’t Work: " + momoCpV1Seed.reports.didnt.join(", ")]} /><ReportSection icon={CalendarCheck} title="Next month focus" items={momoCpV1Seed.reports.nextMonth} /><ReportSection icon={Info} title="Monthly Report Safety" items={["No fake numbers are shown.", "No promises about orders, rankings, profit, ROI, or complicated attribution math are shown.", "Veroxa keeps internal value/profit review out of client reports."]} /></section></PortalLayout>; }
function ReportSection({ icon: Icon, title, items }: { icon: typeof Info; title: string; items: string[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Icon className="h-4 w-4 text-primary" />{title}</CardTitle></CardHeader><CardContent className="space-y-2">{items.map((item) => <p key={item} className="rounded-lg border border-border/70 p-3 text-sm text-muted-foreground">{item}</p>)}</CardContent></Card>; }
