import { Camera, MessageSquare } from "lucide-react";
import { Link } from "wouter";
import { PortalLayout } from "@/components/PortalLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { clientPortalNavItems } from "@/lib/clientPortalNav";
import { getClientPortalHref } from "@/lib/clientPortalRoutes";
import { useRealPortalDataMode } from "@/components/auth/RealPortalDataBoundary";
import { momoCpV1Seed, statusTone } from "@/domain/momoCpV1/momoClientPortalSeed";
export default function ClientMedia() { const mode = useRealPortalDataMode(); const messagesHref = getClientPortalHref("messages", mode.isPublicDemoRoute); return <PortalLayout items={clientPortalNavItems} portalName="Client Portal"><PageHeader title="Media" description="See what media Veroxa recommends, how to send it, and what Veroxa has reviewed already." testId="header-client-media" /><section className="grid gap-4 lg:grid-cols-[1fr_0.9fr]"><Card data-testid="recommended-media"><CardHeader><CardTitle className="text-sm">Recommended Media</CardTitle></CardHeader><CardContent className="space-y-2">{momoCpV1Seed.media.recommendations.map((item) => <div key={item.name} className="rounded-lg border border-border/70 p-3 text-sm"><div className="flex items-start justify-between gap-3"><p className="font-medium">{item.name}</p><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge></div><p className="mt-1 text-muted-foreground">{item.guidance}</p></div>)}</CardContent></Card><Card data-testid="how-to-send-media"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><MessageSquare className="h-4 w-4 text-primary" />How to Send Media</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>Send photos or videos whenever it is easy. They do not need to be perfect. Veroxa will review them and decide what can be used, saved for later, or improved.</p><Link href={messagesHref}><Button variant="outline">Message Veroxa About Media</Button></Link></CardContent></Card></section><Card className="mt-4" data-testid="card-media-detail"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Camera className="h-4 w-4 text-primary" />Media Reviewed by Veroxa</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{momoCpV1Seed.media.reviewed.map((item) => <div key={item.name} className="rounded-lg border border-border/70 p-3"><div className="flex items-start justify-between gap-3"><p className="font-medium">{item.name}</p><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge></div><p className="mt-2 text-xs text-muted-foreground"><span className="font-medium text-foreground">Veroxa Notes:</span> {item.note}</p></div>)}</CardContent></Card></PortalLayout>; }
// Media lifecycle guardrail markers: buildClientSubmissionKey duplicate-skipped.
