import { Link } from "wouter";
import { MessageSquare } from "lucide-react";
import { PortalLayout } from "@/components/PortalLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { clientPortalNavItems } from "@/lib/clientPortalNav";
import { getClientPortalHref } from "@/lib/clientPortalRoutes";
import { useRealPortalDataMode } from "@/components/auth/RealPortalDataBoundary";
import { momoCpV1Seed, statusTone } from "@/domain/momoCpV1/momoClientPortalSeed";
export default function ClientProfile() { const mode = useRealPortalDataMode(); const messagesHref = getClientPortalHref("messages", mode.isPublicDemoRoute); return <PortalLayout items={clientPortalNavItems} portalName="Client Portal"><PageHeader title="Profile" description="Review what Veroxa knows about your restaurant and message Veroxa with anything that should be corrected." testId="header-client-profile" /><Card className="border-primary/20 bg-primary/5"><CardContent className="p-4 text-sm text-muted-foreground">Changes on this review screen are not published or stored as live business updates yet. Please message Veroxa to confirm corrections.</CardContent></Card><section className="grid gap-4 lg:grid-cols-2">{momoCpV1Seed.profile.map((section) => <Card key={section.section}><CardHeader><CardTitle className="text-sm">{section.section}</CardTitle></CardHeader><CardContent className="space-y-3">{section.fields.map((field) => <label key={field.label} className="block space-y-1"><span className="flex items-center justify-between gap-3 text-xs font-medium text-muted-foreground">{field.label}<StatusBadge tone={statusTone(field.status)}>{field.status}</StatusBadge></span><Input readOnly defaultValue={field.value} />{"websiteAccessStatus" in field ? <p className="text-[11px] text-muted-foreground">Website access is optional and only needed if Veroxa is asked to help refine the website.</p> : null}</label>)}</CardContent></Card>)}</section><Card data-testid="profile-correction-path"><CardHeader><CardTitle className="text-sm">Need to correct something?</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>Please message Veroxa with the correction. Veroxa will review changes before using them publicly.</p><Link href={messagesHref}><Button variant="outline"><MessageSquare className="mr-2 h-4 w-4" />Message Veroxa About Profile</Button></Link></CardContent></Card></PortalLayout>; }
