import { useState } from "react";
import { UserRound } from "lucide-react";
import { PortalLayout } from "@/components/PortalLayout";
import { RealPortalReviewNotice } from "@/components/RealPortalSafeStates";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { clientPortalNavItems } from "@/lib/clientPortalNav";
import { momoCpV1Seed, statusTone } from "@/domain/momoCpV1/momoClientPortalSeed";
export default function ClientProfile() { const [edited, setEdited] = useState(false); const fieldStatus = (status:string) => edited && status !== "Confirmed" ? "Pending Veroxa Review" : status; return <PortalLayout items={clientPortalNavItems} portalName="Client Portal"><RealPortalReviewNotice /><PageHeader title="Profile" description="Review pre-filled Momo’s House business details and send corrections to Veroxa for review before any public-facing work is prepared." testId="header-client-profile" />{edited ? <Card className="mb-4 border-amber-500/20 bg-amber-500/5"><CardContent className="p-4 text-sm"><StatusBadge tone="warning">Pending Veroxa Review</StatusBadge><p className="mt-2 text-muted-foreground">Your changes are held in this review-mode screen only. Nothing publishes, stores to a database, or updates Google, Meta, or the website automatically.</p></CardContent></Card> : null}<section className="grid gap-4 lg:grid-cols-2">{momoCpV1Seed.profile.map((section) => <Card key={section.section}><CardHeader><CardTitle className="text-sm">{section.section}</CardTitle></CardHeader><CardContent className="space-y-3">{section.fields.map((field) => <label key={field.label} className="block space-y-1"><span className="flex items-center justify-between gap-3 text-xs font-medium text-muted-foreground">{field.label}<StatusBadge tone={statusTone(fieldStatus(field.status))}>{fieldStatus(field.status)}</StatusBadge></span><Input onChange={() => setEdited(true)} defaultValue={field.value} />{"websiteAccessStatus" in field ? <p className="text-[11px] text-muted-foreground">Website access status: {field.websiteAccessStatus}. Allowed statuses: Not Needed, Requested, Pending, Connected, Access Unavailable.</p> : null}</label>)}</CardContent></Card>)}<Card><CardHeader><CardTitle className="text-sm">Brand Voice</CardTitle></CardHeader><CardContent className="space-y-3"><Textarea onChange={() => setEdited(true)} defaultValue={"Family-friendly, casual, great for first-time momo customers. Catering available only if confirmed. Avoid halal/organic/healthy/spicy/dietary claims unless owner confirms."} /><StatusBadge tone={statusTone(edited ? "Pending Veroxa Review" : "Pre-filled — please review")}>{edited ? "Pending Veroxa Review" : "Pre-filled — please review"}</StatusBadge></CardContent></Card></section><div className="mt-4 flex flex-wrap items-center gap-3"><Button onClick={() => setEdited(true)}><UserRound className="mr-2 h-4 w-4" />Save Changes for Veroxa Review</Button><p className="text-xs text-muted-foreground">Owner edits become Pending Veroxa Review and do not update Google, Meta, website, reports, public content, or any live platform.</p></div></PortalLayout>; }
