export type MomoAiDraftApprovalStatus = "waiting_for_team_review" | "needs_faraz_review" | "needs_business_truth_check" | "needs_media_rights_check" | "needs_sensitive_claim_check" | "needs_owner_confirmation" | "edit_required" | "held" | "rejected" | "eligible_for_manual_execution_review_only" | "blocked_for_public_use" | "future_step_required";
export type MomoAiDraftApprovalRisk = "low" | "medium" | "high" | "critical";
export type MomoAiDraftApprovalCategory = "Queue Overview" | "Review States" | "Business Truth Checks" | "Media Rights Checks" | "Sensitive Claim Checks" | "Brand Voice Checks" | "Team Decision Actions" | "Faraz Escalation Rules" | "Owner Confirmation Needed" | "Manual Execution Readiness" | "Blocked / Rejected States" | "No-Publication Boundaries" | "Safe Internal Next Decision";
export type MomoAiDraftApprovalQueueItem = { id: string; category: MomoAiDraftApprovalCategory; title: string; status: MomoAiDraftApprovalStatus; risk: MomoAiDraftApprovalRisk; description: string; allowed_action: string; blocked_action: string; required_confirmation: string; safe_internal_next_step: string; route_href?: string };

export const MOMO_AI_DRAFT_APPROVAL_CATEGORIES: MomoAiDraftApprovalCategory[] = ["Queue Overview", "Review States", "Business Truth Checks", "Media Rights Checks", "Sensitive Claim Checks", "Brand Voice Checks", "Team Decision Actions", "Faraz Escalation Rules", "Owner Confirmation Needed", "Manual Execution Readiness", "Blocked / Rejected States", "No-Publication Boundaries", "Safe Internal Next Decision"];
export const MOMO_AI_DRAFT_APPROVAL_STATUSES: MomoAiDraftApprovalStatus[] = ["waiting_for_team_review", "needs_faraz_review", "needs_business_truth_check", "needs_media_rights_check", "needs_sensitive_claim_check", "needs_owner_confirmation", "edit_required", "held", "rejected", "eligible_for_manual_execution_review_only", "blocked_for_public_use", "future_step_required"];
export const MOMO_AI_DRAFT_APPROVAL_SAFETY_COPY = ["Internal AI draft approval queue only.", "This does not generate AI output.", "This does not call any AI provider.", "This does not auto-approve AI output.", "This does not publish AI output.", "This does not expose AI output to the client.", "This does not activate the pilot.", "This does not turn on real auth.", "This does not create credentials.", "This does not contact Momo’s House.", "This does not upload, create, seed, generate, or fake media.", "This does not publish externally.", "This does not connect Google, Meta, Yelp, TikTok, or delivery platforms.", "AI drafts may move forward only after Team/Faraz review.", "Business-truth changes still require owner confirmation.", "Media usage rights require owner confirmation before public use.", "Sensitive claims are blocked until owner-confirmed.", "Momo owner walkthrough remains blocked.", "No next activation PR is approved by default.", "Future real-world activation requires separate explicit Faraz approval."];
export const MOMO_AI_DRAFT_APPROVAL_ALLOWED_TEAM_LINKS = ["/team/momo-ai-generation", "/team/momo-brand-ai-rules", "/team/momo-media-content", "/team/momo-business-truth", "/team/momo-pilot-prep", "/team/momo-live-readiness", "/team/momo-activation-gate", "/team/control-center", "/team/profile-corrections", "/team/upload-inbox", "/team/messages", "/team/activity-log", "/team/ai-drafts", "/team/reports-from-activity"];

const shared = { allowed_action: "Team may hold, reject, request edit, escalate to Faraz, or mark eligible for manual execution review only.", blocked_action: "No approval for publishing, no external send, no owner/client outreach, no platform connection, no auto-approval, and no automated execution.", required_confirmation: "Owner confirmation is required before business-truth changes, media usage rights, sensitive claims, or public/customer-visible use.", safe_internal_next_step: "Review internally, keep publishing blocked, keep owner walkthrough blocked, and require separate explicit Faraz approval for future activation." };
export const MOMO_AI_DRAFT_APPROVAL_QUEUE_ITEMS: MomoAiDraftApprovalQueueItem[] = [
{ id:"queue-purpose", category:"Queue Overview", title:"Internal Team review only", status:"waiting_for_team_review", risk:"critical", description:"The queue defines how future AI drafts are controlled before any manual execution consideration. AI drafts are not customer-visible, not automatically approved, not published, and every draft must pass checks first.", ...shared },
{ id:"review-states", category:"Review States", title:"Approval states remain internal blockers", status:"waiting_for_team_review", risk:"high", description:"States include waiting_for_team_review, needs_faraz_review, needs_business_truth_check, needs_media_rights_check, needs_sensitive_claim_check, needs_owner_confirmation, edit_required, held, rejected, eligible_for_manual_execution_review_only, and blocked_for_public_use.", ...shared },
{ id:"business-truth", category:"Business Truth Checks", title:"Business truth blockers", status:"needs_business_truth_check", risk:"critical", description:"Hold or block drafts that reference unconfirmed menu items, prices, hours, address, phone, order links, delivery, catering, halal/dietary/sensitive claims, awards, rankings, popularity, platform status, availability, offers, or promotions.", route_href:"/team/momo-business-truth", ...shared },
{ id:"media-rights", category:"Media Rights Checks", title:"Media usage blockers", status:"needs_media_rights_check", risk:"critical", description:"Hold or block drafts referencing media without confirmed media existence, usage rights confirmation required, staff/customer face consent if needed, dish availability confirmation, truthful context, and no fake/generated media.", route_href:"/team/momo-media-content", ...shared },
{ id:"sensitive-claims", category:"Sensitive Claim Checks", title:"Sensitive claims blocked until owner-confirmed", status:"needs_sensitive_claim_check", risk:"critical", description:"Block halal, vegetarian/vegan, allergen-free, gluten-free, health, authentic/origin, family-owned, awards/certifications, religious/cultural, ownership background, and identity claims unless owner-confirmed and Team/Faraz approved.", ...shared },
{ id:"brand-voice", category:"Brand Voice Checks", title:"PR #117 brand rules", status:"edit_required", risk:"medium", description:"Drafts must stay warm, simple, crave-focused, local, approachable, first-timer friendly, and food-forward with no fake urgency, fake discounts, fake reviews, fake popularity, overpromising, or offensive cultural/food/religion jokes.", route_href:"/team/momo-brand-ai-rules", ...shared },
{ id:"team-decisions", category:"Team Decision Actions", title:"Allowed internal decisions only", status:"needs_faraz_review", risk:"high", description:"Allowed decisions are hold, reject, request edit, needs Faraz review, needs owner confirmation later, or mark eligible for manual execution review only.", ...shared },
{ id:"faraz-escalation", category:"Faraz Escalation Rules", title:"Escalate risky drafts to Faraz", status:"needs_faraz_review", risk:"critical", description:"Escalate when a sensitive claim appears, reputation risk exists, unconfirmed business truth affects copy, brand/tone risk is high, owner confirmation is needed, manual execution is being considered, or anything could become customer-visible.", ...shared },
{ id:"owner-confirmation", category:"Owner Confirmation Needed", title:"Future blocker only", status:"needs_owner_confirmation", risk:"critical", description:"Owner confirmation needed is a future blocker only. It does not create outreach, send to owner, unlock walkthrough, or imply anything has been confirmed.", ...shared },
{ id:"manual-review", category:"Manual Execution Readiness", title:"Eligible for manual execution review only", status:"eligible_for_manual_execution_review_only", risk:"high", description:"A draft can reach this only after business truth, media rights, sensitive claims, Team review, and Faraz review where risk exists are cleared; no external platform action is automated and no publishing happens from this PR.", ...shared },
{ id:"blocked-rejected", category:"Blocked / Rejected States", title:"Block or reject unsafe drafts", status:"blocked_for_public_use", risk:"critical", description:"Reject or block invented facts, fake offers, fake claims, unconfirmed prices/hours/menu, unconfirmed media rights, sensitive claims without confirmation, unsupported platform claims, customer-visible instruction, raw AI hallucination, or unsafe tone.", ...shared },
{ id:"no-publication", category:"No-Publication Boundaries", title:"No publication controls", status:"blocked_for_public_use", risk:"critical", description:"There is no publish button, no post button, no external send, no client visibility, no owner visibility, no platform sync, no schedule job, no auto-approval, and no automated execution.", ...shared },
{ id:"safe-next", category:"Safe Internal Next Decision", title:"Next decision remains internal", status:"future_step_required", risk:"high", description:"Faraz reviews approval queue rules, Team decides which approval states are sufficient for a next PR, publishing stays blocked, owner walkthrough stays blocked, and no external action occurs from this PR.", ...shared },
];
