// Dormant readiness only — no live AI call is made here.

import type { AiReadinessSuggestion } from "./types";

const planningLabel = "Internal planning only. No live AI generated this. Not client-visible unless reviewed later.";

export const aiReadinessSeedSuggestions: AiReadinessSuggestion[] = [
  {
    id: "seed-media-review-001",
    assistantType: "media_review",
    status: "draft_only",
    visibility: "internal_only",
    confidence: "medium",
    requiredReviews: ["veroxa_team_review", "faraz_review"],
    clientSafeSummary: `${planningLabel} Food close-up appears usable after human review.`,
    internalNotes: "Use as a planning example for media usefulness suggestions only.",
    blockedReasons: [],
    createdAt: "2026-06-06T00:00:00.000Z",
    usefulnessSuggestion: "Likely usable for a simple Google or Instagram update after review.",
    nextClientAsk: "Ask for one brighter photo of the same item if available.",
    contentDirection: "Keep copy factual and based on confirmed item details only.",
  },
  {
    id: "seed-caption-draft-001",
    assistantType: "caption_draft",
    status: "needs_human_review",
    visibility: "internal_only",
    confidence: "low",
    requiredReviews: ["veroxa_team_review", "faraz_review", "business_truth_confirmation"],
    clientSafeSummary: `${planningLabel} Caption drafts are placeholders until item details are confirmed.`,
    internalNotes: "Do not use with a real restaurant until the item name and facts are confirmed.",
    blockedReasons: ["Confirmed item details are required before client visibility."],
    createdAt: "2026-06-06T00:00:00.000Z",
    captions: [
      "A fresh look at one of the kitchen favorites. Confirm the item name before posting.",
      "Prepared with care and ready for a simple spotlight once details are confirmed.",
      "A clean food photo can help guests know what to look for before they visit or order.",
    ],
    businessTruthNeeds: ["Confirm item name.", "Confirm whether any offer exists before mentioning it."],
  },
  {
    id: "seed-weekly-update-001",
    assistantType: "weekly_update_draft",
    status: "draft_only",
    visibility: "internal_only",
    confidence: "medium",
    requiredReviews: ["veroxa_team_review", "faraz_review"],
    clientSafeSummary: `${planningLabel} Weekly update draft summarizes reviewed work without metrics.`,
    internalNotes: "No fake progress or metrics are included.",
    blockedReasons: [],
    createdAt: "2026-06-06T00:00:00.000Z",
    updateDraft: "This week Veroxa prepared visibility updates, reviewed available media, and noted what still needs confirmation before anything goes live.",
    missingInputs: ["Confirm any changed hours before public copy is prepared."],
  },
  {
    id: "seed-monthly-report-001",
    assistantType: "monthly_report_draft",
    status: "draft_only",
    visibility: "internal_only",
    confidence: "not_applicable",
    requiredReviews: ["veroxa_team_review", "faraz_review"],
    clientSafeSummary: `${planningLabel} Monthly report draft states when there is not enough data.`,
    internalNotes: "Use only as a structure example; do not add proof math or generated-sales claims.",
    blockedReasons: [],
    createdAt: "2026-06-06T00:00:00.000Z",
    reportDraft: "There is not enough data yet to read trends confidently. This report should focus on work completed, visibility cleanup, media needs, and next-month priorities.",
    dataLimitations: ["No reliable trend data available in this planning example."],
  },
  {
    id: "seed-request-classification-001",
    assistantType: "request_classification",
    status: "draft_only",
    visibility: "internal_only",
    confidence: "medium",
    requiredReviews: ["veroxa_team_review", "faraz_review"],
    clientSafeSummary: `${planningLabel} Request classification suggestion defers to packageBoundary rules.`,
    internalNotes: "No upgrade or payment flow is created by this suggestion.",
    blockedReasons: [],
    createdAt: "2026-06-06T00:00:00.000Z",
    suggestedClassification: "needs_review",
    packageBoundaryRule: "Defer to packageBoundary domain before deciding included, add-on, coming-soon, or not-included.",
  },
  {
    id: "seed-internal-qa-001",
    assistantType: "internal_qa",
    status: "draft_only",
    visibility: "never_client_visible",
    confidence: "not_applicable",
    requiredReviews: ["veroxa_team_review", "faraz_review"],
    clientSafeSummary: `${planningLabel} Internal QA checklist is never client-visible.`,
    internalNotes: "Advisory checklist only; it must not alter output automatically.",
    blockedReasons: [],
    createdAt: "2026-06-06T00:00:00.000Z",
    checklist: [
      "Check for guarantee language.",
      "Check for unconfirmed business facts.",
      "Check for internal proof math leakage.",
      "Check that Veroxa team review remains required.",
    ],
    riskSummary: "Planning example for policy review before any future sharing.",
  },
];
