import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
const root = process.cwd().endsWith("/scripts") ? join(process.cwd(), "..") : process.cwd();
const read = (p: string) => readFileSync(join(root, p), "utf8");
const failures: string[] = [];
const must = (ok: boolean, msg: string) => { if (!ok) failures.push(msg); };
const authMode = read("artifacts/veroxa/src/lib/auth/authMode.ts");
const pilotAccess = read("artifacts/veroxa/src/lib/auth/pilotAccessAccounts.ts");
const app = read("artifacts/veroxa/src/App.tsx");
const nav = read("artifacts/veroxa/src/lib/teamPortalNav.ts");
const page = read("artifacts/veroxa/src/pages/team-momo-dry-run-go-no-go.tsx");
const model = read("artifacts/veroxa/src/lib/momoDryRun/momoInternalDryRunGoNoGo.ts");
const control = read("artifacts/veroxa/src/pages/team-control-center.tsx");
const approval = existsSync(join(root, "artifacts/veroxa/src/pages/team-momo-ai-approval.tsx")) ? read("artifacts/veroxa/src/pages/team-momo-ai-approval.tsx") : "";
const generation = read("artifacts/veroxa/src/pages/team-momo-ai-generation.tsx");
const readiness = read("artifacts/veroxa/src/pages/team-momo-live-readiness.tsx");
const activation = read("artifacts/veroxa/src/pages/team-momo-activation-gate.tsx");
must(/AUTH_MODE\s*:\s*AuthMode\s*=\s*["']placeholder["']/.test(authMode), "AUTH_MODE must remain placeholder.");
must(pilotAccess.includes("/api/pilot-access"), "/api/pilot-access remains active.");
must(app.includes('path="/team/momo-dry-run-go-no-go"'), "Team dry-run route exists.");
const block = app.slice(app.indexOf('path="/team/momo-dry-run-go-no-go"'), app.indexOf('path="/team/momo-activation-gate"'));
must(block.includes('<InternalDemoGuard role="team">'), "Route guarded by InternalDemoGuard role=team.");
must(block.includes('<RealPortalDataBoundary portal="team">'), "Route wrapped in RealPortalDataBoundary portal=team.");
must(nav.includes("Momo Dry Run") && nav.includes("/team/momo-dry-run-go-no-go"), "Team nav includes Momo Dry Run.");
must(control.includes("Momo Dry Run") && control.includes("PR #120") && control.includes("/team/momo-dry-run-go-no-go"), "Control Center links to dry run.");
for (const source of [approval, generation, readiness, activation]) must(source.includes("/team/momo-dry-run-go-no-go"), "Related Momo pages link safely to dry-run gate.");
must(!app.includes('path="/client/momo-dry-run-go-no-go"'), "No client dry-run route.");
must(!existsSync(join(root, "artifacts/veroxa/src/pages/client-momo-dry-run-go-no-go.tsx")), "No client dry-run page.");
must(!/owner.*walkthrough.*path=/i.test(app), "No owner walkthrough route.");
must(!/role\s*===\s*["'](owner|operator|admin|super_admin|execution)["']/.test([app, nav, page, model].join("\n")), "No new roles beyond client/team.");
for (const marker of ["Internal dry run and go/no-go review only.", "This does not activate the pilot.", "This does not turn on real auth.", "This does not create credentials.", "This does not contact Momo’s House.", "This does not expose anything to the client.", "This does not generate AI output.", "This does not create fake AI drafts.", "This does not create fake approvals.", "This does not create fake reports.", "This does not upload, create, seed, generate, or fake media.", "This does not publish externally.", "This does not connect Google, Meta, Yelp, TikTok, or delivery platforms.", "Business-truth changes still require owner confirmation.", "Media usage rights require owner confirmation before public use.", "Sensitive claims are blocked until owner-confirmed.", "Momo owner walkthrough remains blocked.", "No next activation PR is approved by default.", "Future real-world activation requires separate explicit Faraz approval."]) must(page.includes(marker) || model.includes(marker), `Missing safety copy: ${marker}`);
for (const marker of ["Dry Run Scope", "Preflight Requirements", "Business Truth Readiness", "Media Content Readiness", "Brand AI Readiness", "AI Generation Readiness", "AI Approval Readiness", "Activity Log Readiness", "Report Readiness", "Client Visibility Boundaries", "Real Auth / Access Blockers", "No-Publication Boundaries", "Go / No-Go Decision", "Safe Internal Next Decision"]) must(model.includes(marker), `Model missing ${marker}`);
for (const marker of ["no_go", "blocked", "needs_faraz_review", "ready_for_internal_dry_run_only", "go_for_internal_review_only", "future_step_required"]) must(model.includes(marker), `Allowed state missing ${marker}`);
const active = page + "\n" + model;
must(!/ready_to_launch|ready_for_owner_walkthrough|ready_for_client|ready_to_publish|production_ready/.test(active), "Forbidden decision labels in active UI/model code.");
must(!/\.insert\(|\.update\(|\.delete\(|\.upsert\(/.test(active), "No DB writes in dry-run code.");
must(!/openai|anthropic|gemini|apiKey|service_role|platform token|stripe|checkout|OAuth/i.test(active), "No provider keys, tokens, OAuth, or payments in dry-run code.");
must(!/storage\.from|cron\s*\(|webhook\s*\(|backgroundJob|scheduledJob/i.test(active), "No storage, cron, webhooks, or jobs in dry-run code.");
const docs = ["MOMO_INTERNAL_DRY_RUN_GO_NO_GO_GATE.md", "ACTIVE_DOCS_INDEX.md", "LIVE_AUTOMATION_V1_PR_SEQUENCE.md", "VEROXA_LOCKED_OPERATING_MEMORY.md", "CURRENT_BUILD_STATUS.md"].map((f) => read(`artifacts/veroxa/docs/${f}`)).join("\n");
for (const marker of ["PR #120", "Momo Internal Dry Run + Go/No-Go Gate", "internal dry-run/go-no-go review only", "AUTH_MODE remains placeholder", "/api/pilot-access remains active", "Momo owner walkthrough remains blocked", "No next activation PR is approved by default", "Future real-world activation requires separate explicit Faraz approval"]) must(docs.includes(marker), `Docs missing ${marker}`);
must(read("artifacts/veroxa/docs/ACTIVE_DOCS_INDEX.md").includes("MOMO_INTERNAL_DRY_RUN_GO_NO_GO_GATE.md"), "Active Docs Index lists dry-run doc.");
if (failures.length) { console.error(failures.map((f) => `- ${f}`).join("\n")); process.exit(1); }
console.log("Momo Internal Dry Run + Go/No-Go Gate guardrail passed.");
