import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
const root = process.cwd().endsWith("/scripts") ? join(process.cwd(), "..") : process.cwd();
const read = (p: string) => readFileSync(join(root, p), "utf8");
const failures: string[] = [];
const must = (ok: boolean, msg: string) => { if (!ok) failures.push(msg); };
const authMode = read("artifacts/veroxa/src/lib/auth/authMode.ts");
const pilotAccess = read("artifacts/veroxa/src/lib/auth/pilotAccessAccounts.ts");
const app = read("artifacts/veroxa/src/App.tsx");
const nav = read("artifacts/veroxa/src/lib/teamPortalNav.ts");
const page = read("artifacts/veroxa/src/pages/team-momo-ai-approval.tsx");
const model = read("artifacts/veroxa/src/lib/momoAiDraftApproval/momoAiDraftApprovalQueue.ts");
const control = read("artifacts/veroxa/src/pages/team-control-center.tsx");
const generation = read("artifacts/veroxa/src/pages/team-momo-ai-generation.tsx");
const brand = read("artifacts/veroxa/src/pages/team-momo-brand-ai-rules.tsx");
const aiDrafts = read("artifacts/veroxa/src/pages/team-ai-drafts.tsx");
must(/AUTH_MODE\s*:\s*AuthMode\s*=\s*["']placeholder["']/.test(authMode), "AUTH_MODE must remain placeholder.");
must(pilotAccess.includes("/api/pilot-access"), "/api/pilot-access remains active.");
must(app.includes('path="/team/momo-ai-approval"'), "Team Momo AI approval route exists.");
const block = app.slice(app.indexOf('path="/team/momo-ai-approval"'), app.indexOf('path="/team/momo-activation-gate"'));
must(block.includes('<InternalDemoGuard role="team">'), "Route guarded by InternalDemoGuard role=team.");
must(block.includes('<RealPortalDataBoundary portal="team">'), "Route wrapped in RealPortalDataBoundary portal=team.");
must(nav.includes("Momo AI Approval") && nav.includes("/team/momo-ai-approval"), "Team nav includes Momo AI Approval.");
must(control.includes("Momo AI Approval") && control.includes("PR #119") && control.includes("/team/momo-ai-approval"), "Control Center links to Momo AI Approval.");
must(generation.includes("/team/momo-ai-approval") && /Review AI approval queue|Open internal AI approval queue|Review AI draft approval blockers/.test(generation), "Momo AI Generation links safely.");
must(brand.includes("/team/momo-ai-approval"), "Momo Brand AI Rules links safely.");
must(aiDrafts.includes("/team/momo-ai-approval"), "AI Drafts page links safely.");
must(!app.includes('path="/client/momo-ai-approval"'), "No client Momo AI approval route.");
must(!existsSync(join(root, "artifacts/veroxa/src/pages/client-momo-ai-approval.tsx")), "No client page.");
must(!/owner.*walkthrough.*path=/i.test(app), "No owner walkthrough route.");
must(!/role\s*===\s*["'](owner|operator|admin|super_admin|execution)["']/.test([app, nav, page, model].join("\n")), "No new roles beyond client/team.");
for (const marker of ["Internal AI draft approval queue only.", "This does not generate AI output.", "This does not call any AI provider.", "This does not auto-approve AI output.", "This does not publish AI output.", "This does not expose AI output to the client.", "This does not activate the pilot.", "This does not turn on real auth.", "This does not create credentials.", "This does not contact Momo’s House.", "This does not upload, create, seed, generate, or fake media.", "This does not publish externally.", "This does not connect Google, Meta, Yelp, TikTok, or delivery platforms.", "AI drafts may move forward only after Team/Faraz review.", "Business-truth changes still require owner confirmation.", "Media usage rights require owner confirmation before public use.", "Sensitive claims are blocked until owner-confirmed.", "Momo owner walkthrough remains blocked.", "No next activation PR is approved by default.", "Future real-world activation requires separate explicit Faraz approval."]) must(page.includes(marker) || model.includes(marker), `Page missing safety copy: ${marker}`);
for (const marker of ["Queue Overview", "Review States", "Business Truth Checks", "Media Rights Checks", "Sensitive Claim Checks", "Brand Voice Checks", "Team Decision Actions", "Faraz Escalation Rules", "Owner Confirmation Needed", "Manual Execution Readiness", "Blocked / Rejected States", "No-Publication Boundaries", "Safe Internal Next Decision"]) must(model.includes(marker), `Approval model missing ${marker}`);
for (const marker of ["waiting_for_team_review", "needs_faraz_review", "needs_business_truth_check", "needs_media_rights_check", "needs_sensitive_claim_check", "needs_owner_confirmation", "edit_required", "held", "rejected", "eligible_for_manual_execution_review_only", "blocked_for_public_use"]) must(model.includes(marker), `Review state missing ${marker}`);
const approvalCode = page + "\n" + model;
must(!/\.insert\(|\.update\(|\.delete\(|\.upsert\(/.test(approvalCode), "No DB writes in approval code.");
must(!/openai|anthropic|gemini|apiKey|service_role|platform token|stripe|checkout|OAuth/i.test(approvalCode), "No provider keys, service roles, tokens, OAuth, or payments in approval code.");
must(!/createAiDraftRecord|storage\.from|cron\s*\(|webhook\s*\(|backgroundJob|scheduledJob/i.test(approvalCode), "No draft creation, storage, cron, webhooks, or jobs in approval code.");
must(!/approve for publishing|post content|generate AI now|generate caption now|call AI provider now|turn on real auth|owner walkthrough can begin|activation approved|real auth activation approved|usage rights confirmed|media rights confirmed|confirmed by owner|fake readiness|fake metrics|fake reports|fake activity|fake AI output|fake approval/i.test(page), "Unsafe active-code phrase appears on page.");
const docs = ["MOMO_AI_DRAFT_APPROVAL_QUEUE.md", "ACTIVE_DOCS_INDEX.md", "LIVE_AUTOMATION_V1_PR_SEQUENCE.md", "VEROXA_LOCKED_OPERATING_MEMORY.md", "CURRENT_BUILD_STATUS.md"].map((f) => read(`artifacts/veroxa/docs/${f}`)).join("\n");
for (const marker of ["PR #119", "AI Draft Approval Queue", "internal AI draft approval queue only", "AUTH_MODE remains placeholder", "/api/pilot-access remains active", "Momo owner walkthrough remains blocked", "No next activation PR is approved by default", "Future real-world activation requires separate explicit Faraz approval"]) must(docs.includes(marker), `Docs missing ${marker}`);
const index = read("artifacts/veroxa/docs/ACTIVE_DOCS_INDEX.md");
for (const doc of ["MOMO_AI_DRAFT_APPROVAL_QUEUE.md", "MOMO_CONTROLLED_AI_DRAFT_GENERATION_FOUNDATION.md", "MOMO_BRAND_VOICE_AI_PROMPT_RULES.md", "MOMO_MEDIA_CONTENT_INVENTORY_PACK.md", "MOMO_BUSINESS_TRUTH_REVIEW_PACK.md"]) must(index.includes(doc), `Active Docs Index lists ${doc}`);
if (failures.length) { console.error(failures.map((f) => `- ${f}`).join("\n")); process.exit(1); }
console.log("Momo AI Draft Approval Queue guardrail passed.");
