import { readFileSync } from "node:fs";
import { join } from "node:path";
const cwd = process.cwd();
const root = cwd.endsWith("/scripts") ? join(cwd, "..") : cwd;
const read = (p: string) => readFileSync(join(root, p), "utf8");
const failures: string[] = [];
const must = (ok: boolean, msg: string) => { if (!ok) failures.push(msg); };
const authMode = read("artifacts/veroxa/src/lib/auth/authMode.ts");
const login = read("artifacts/veroxa/src/pages/login.tsx");
const pilotAccess = read("artifacts/veroxa/src/lib/auth/pilotAccessAccounts.ts");
const config = read("artifacts/veroxa/src/lib/momoReadiness/momoReadinessConfig.ts");
const service = read("artifacts/veroxa/src/lib/momoReadiness/momoReadinessService.ts");
const page = read("artifacts/veroxa/src/pages/team-momo-live-readiness.tsx");
const app = read("artifacts/veroxa/src/App.tsx");
const nav = read("artifacts/veroxa/src/lib/teamPortalNav.ts");
const pkg = read("package.json");
const docs = ["artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MOMO_READINESS_GATE.md","artifacts/veroxa/docs/ACTIVE_DOCS_INDEX.md","artifacts/veroxa/docs/LIVE_AUTOMATION_V1_PR_SEQUENCE.md","artifacts/veroxa/docs/VEROXA_LOCKED_OPERATING_MEMORY.md","artifacts/veroxa/docs/CURRENT_BUILD_STATUS.md","artifacts/veroxa/docs/LIVE_AUTOMATION_V1_ARCHITECTURE.md","artifacts/veroxa/docs/ROUTE_PAGE_INVENTORY.md","artifacts/veroxa/docs/VEROXA_ROUTE_SURFACE_MAP.md"].map(read).join("\n");

must(/AUTH_MODE\s*:\s*AuthMode\s*=\s*["']placeholder["']/.test(authMode), "AUTH_MODE must remain placeholder.");
must(/pilot-access/.test(login + pilotAccess), "/api/pilot-access must remain active.");
must(config.includes('AUTH_MODE === "real"'), "Feature gate requires AUTH_MODE real.");
must(config.includes("VITE_VEROXA_MOMO_READINESS_GATE_ENABLED"), "Feature gate requires Momo readiness flag.");
must(config.includes('auth.status === "authenticated"') && config.includes('role === "team"'), "Feature gate requires authenticated Team role.");
must(app.includes('path="/team/momo-live-readiness"'), "Team Momo readiness route exists.");
const blockStart = app.indexOf('path="/team/momo-live-readiness"');
const blockEnd = app.indexOf('path="/team/approval-queue"');
const block = app.slice(blockStart, blockEnd > blockStart ? blockEnd : undefined);
must(block.includes('<InternalDemoGuard role="team">'), "Momo readiness route must be guarded by InternalDemoGuard role=team.");
must(block.includes('<RealPortalDataBoundary portal="team">'), "Momo readiness route must be wrapped in RealPortalDataBoundary portal=team.");
must(nav.includes("Momo Readiness") && nav.includes("/team/momo-live-readiness"), "Team nav includes /team/momo-live-readiness.");
must(!app.includes('path="/client/momo-live-readiness"'), "No client Momo readiness route.");
must(!pkg.includes("/client/momo-live-readiness"), "No client Momo readiness page marker.");
must(!/role\s*===\s*["'](owner|operator|admin|super_admin)["']/.test([config, service, page, app, nav].join("\n")), "No new roles beyond client/team in PR #109 code.");
must(service.includes('from("restaurants")') && service.includes('"media_assets"') && service.includes('"messages"') && service.includes('"activity_log"') && service.includes('"ai_drafts"') && service.includes('"reports"'), "Readiness service reads existing safe modules.");
must(!/\.insert\(|\.update\(|\.upsert\(|\.delete\(/.test(service), "Readiness service is read-only.");
const activeCode = [config, service, page].join("\n");
const forbidden = [/go live now/i,/start pilot/i,/send to owner/i,/sync Google/i,/sync Meta/i,/connect Instagram/i,/connect Facebook/i,/create auth user/i,/invite client/i,/\bcron\b/i,/webhook/i,/background job/i,/scheduled job/i,/stripe/i,/checkout/i,/service_role/i,/fake readiness/i,/fake metrics/i,/fake reports/i,/fake activity/i,/platform token/i];
for (const pattern of forbidden) must(!pattern.test(activeCode), `Forbidden active-code phrase found: ${pattern}`);
must(!/Google Business Profile API|Meta Business Suite API|Yelp API|TikTok API/i.test(activeCode), "No external connector activation language in active code.");
must(page.includes("Readiness gate only.") && page.includes("This does not activate the pilot.") && page.includes("This does not contact Momo’s House.") && page.includes("This does not publish externally."), "Page includes required safe copy.");
for (const marker of ["GitHub PR #109", "Momo Live Pilot Readiness Gate", "PR #108 Reports From Activity is already merged", "PR #110", "AUTH_MODE", "placeholder", "/api/pilot-access", "Momo owner walkthrough remains blocked", "does not activate real auth", "does not contact Momo’s House", "does not publish externally", "does not create platform integrations", "webhooks, cron jobs, or background jobs"]) must(docs.includes(marker), `Docs missing ${marker}.`);
if (failures.length) { console.error(failures.map((f) => `- ${f}`).join("\n")); process.exit(1); }
console.log("Live Automation V1 Momo Readiness Gate guardrail passed.");
