import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
const cwd = process.cwd();
const root = cwd.endsWith("/scripts") ? join(cwd, "..") : cwd;
const read = (path: string) => readFileSync(join(root, path), "utf8");
const failures: string[] = [];
const must = (condition: boolean, message: string) => { if (!condition) failures.push(message); };
const authMode = read("artifacts/veroxa/src/lib/auth/authMode.ts");
const pilotAccess = read("artifacts/veroxa/src/lib/auth/pilotAccessAccounts.ts");
const app = read("artifacts/veroxa/src/App.tsx");
const nav = read("artifacts/veroxa/src/lib/teamPortalNav.ts");
const page = read("artifacts/veroxa/src/pages/team-momo-brand-ai-rules.tsx");
const model = read("artifacts/veroxa/src/lib/momoBrandAi/momoBrandAiRules.ts");
const controlCenter = read("artifacts/veroxa/src/pages/team-control-center.tsx");
const prepPage = read("artifacts/veroxa/src/pages/team-momo-pilot-prep.tsx");
const truthPage = read("artifacts/veroxa/src/pages/team-momo-business-truth.tsx");
const mediaPage = read("artifacts/veroxa/src/pages/team-momo-media-content.tsx");
const pkg = read("package.json");
const scriptsPkg = read("scripts/package.json");
const docs = ["artifacts/veroxa/docs/MOMO_BRAND_VOICE_AI_PROMPT_RULES.md", "artifacts/veroxa/docs/ACTIVE_DOCS_INDEX.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_PR_SEQUENCE.md", "artifacts/veroxa/docs/VEROXA_LOCKED_OPERATING_MEMORY.md", "artifacts/veroxa/docs/CURRENT_BUILD_STATUS.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_ARCHITECTURE.md", "artifacts/veroxa/docs/MOMO_INTERNAL_PILOT_PREP_PACK.md", "artifacts/veroxa/docs/MOMO_BUSINESS_TRUTH_REVIEW_PACK.md", "artifacts/veroxa/docs/MOMO_MEDIA_CONTENT_INVENTORY_PACK.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MEDIA_UPLOAD_STORAGE.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_AI_DRAFT_PREPARATION.md", "artifacts/veroxa/docs/ROUTE_PAGE_INVENTORY.md", "artifacts/veroxa/docs/VEROXA_ROUTE_SURFACE_MAP.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MOMO_READINESS_GATE.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MOMO_ACTIVATION_GATE.md"].map(read).join("\n");
must(/AUTH_MODE\s*:\s*AuthMode\s*=\s*["']placeholder["']/.test(authMode), "AUTH_MODE must remain placeholder.");
must(pilotAccess.includes("/api/pilot-access"), "/api/pilot-access must remain active.");
must(app.includes('path="/team/momo-brand-ai-rules"'), "Team route exists.");
const start = app.indexOf('path="/team/momo-brand-ai-rules"');
const end = app.indexOf('path="/team/momo-activation-gate"');
const block = app.slice(start, end > start ? end : undefined);
must(block.includes('<InternalDemoGuard role="team">'), "Route guarded by InternalDemoGuard role=team.");
must(block.includes('<RealPortalDataBoundary portal="team">'), "Route wrapped in RealPortalDataBoundary portal=team.");
must(nav.includes("Momo Brand AI") && nav.includes("/team/momo-brand-ai-rules"), "Team nav includes Momo Brand AI.");
must(controlCenter.includes("Momo Brand AI Rules") && controlCenter.includes("PR #117") && controlCenter.includes("/team/momo-brand-ai-rules"), "Control Center links to route.");
must(prepPage.includes("Review brand/AI rules internally") && prepPage.includes("/team/momo-brand-ai-rules"), "Momo Prep links safely.");
must(truthPage.includes("Open internal brand voice and AI rules") && truthPage.includes("/team/momo-brand-ai-rules"), "Momo Business Truth links safely.");
must(mediaPage.includes("Review AI drafting boundaries") && mediaPage.includes("/team/momo-brand-ai-rules"), "Momo Media Content links safely.");
must(!app.includes('path="/client/momo-brand-ai-rules"'), "No client route exists.");
must(!existsSync(join(root, "artifacts/veroxa/src/pages/client-momo-brand-ai-rules.tsx")), "No client page exists.");
must(!/path=["']\/team\/.*owner.*walkthrough/i.test(app), "No owner walkthrough route exists.");
must(!/role\s*===\s*["'](owner|operator|admin|super_admin|execution)["']/.test([app, nav, page, model].join("\n")), "No new roles beyond client/team.");
for (const phrase of ["Internal brand voice and AI prompt-rule preparation only.", "This does not generate AI output.", "This does not call any AI provider.", "This does not activate the pilot.", "This does not turn on real auth.", "This does not create credentials.", "This does not contact Momo’s House.", "This does not upload, create, seed, generate, or fake media.", "This does not publish externally.", "This does not connect Google, Meta, Yelp, TikTok, or delivery platforms.", "AI may use only confirmed business truth and permissioned media in later internal drafts.", "Business-truth changes still require owner confirmation.", "Media usage rights require owner confirmation before public use.", "Sensitive claims are blocked until owner-confirmed.", "All future AI output requires Team/Faraz review before customer-visible use.", "Momo owner walkthrough remains blocked.", "No next activation PR is approved by default.", "Future real-world activation requires separate explicit Faraz approval."]) must(page.includes(phrase), `Page missing required safety copy: ${phrase}`);
for (const category of ["Brand Voice Foundation", "Approved Tone", "Unsafe Tone", "Content Pillar Prompt Rules", "Caption Drafting Rules", "Local SEO Rules", "Sensitive Claim Rules", "Media Dependency Rules", "Business Truth Dependency Rules", "AI Forbidden Outputs", "Prompt Template Boundaries", "Team Review Requirements", "Future Confirmation Questions", "Safe Internal Next Decision"]) must(model.includes(category), `Model missing category: ${category}`);
for (const pillar of ["Momo Cravings", "First-Time Education", "Behind The Scenes", "Customer / Reaction Content", "Snack Discovery", "Local SEO", "Sauce"]) must(model.includes(pillar), `Missing pillar: ${pillar}`);
must(!/\.insert\(|\.update\(|\.upsert\(|\.delete\(/.test([page, model].join("\n")), "No DB writes in brand/AI code.");
must(!readdirSync(join(root, "artifacts/veroxa")).includes("supabase"), "No database migration folder added under artifacts/veroxa.");
const activeCode = [app, nav, page, model, controlCenter, prepPage, truthPage, mediaPage].join("\n");
for (const pattern of [/go live now/i, /pilot activated/i, /owner walkthrough can begin/i, /activation approved/i, /real auth activation approved/i, /service_role/i, /platform token/i, /\.insert\(/, /\.update\(/, /\.upsert\(/, /\.delete\(/]) must(!pattern.test(activeCode), `Forbidden active-code pattern found: ${pattern}`);
for (const marker of ["GitHub PR #117", "Momo Brand Voice + AI Prompt Rules Pack", "internal brand voice and AI prompt-rule preparation only", "AUTH_MODE remains placeholder", "/api/pilot-access remains active", "Momo owner walkthrough remains blocked", "No next activation PR is approved by default", "Future real-world activation requires separate explicit Faraz approval"]) must(docs.includes(marker), `Docs missing ${marker}.`);
for (const doc of ["MOMO_BRAND_VOICE_AI_PROMPT_RULES.md", "MOMO_MEDIA_CONTENT_INVENTORY_PACK.md", "MOMO_BUSINESS_TRUTH_REVIEW_PACK.md"]) must(read("artifacts/veroxa/docs/ACTIVE_DOCS_INDEX.md").includes(doc), `Active Docs Index lists ${doc}.`);
must(scriptsPkg.includes("check-momo-brand-voice-ai-prompt-rules"), "scripts package wires guardrail.");
must(pkg.includes("check-momo-brand-voice-ai-prompt-rules"), "root verify:veroxa wires guardrail.");
if (failures.length) { console.error(failures.map((f) => `- ${f}`).join("\n")); process.exit(1); }
console.log("Momo Brand Voice + AI Prompt Rules Pack guardrail passed.");
