import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
const cwd = process.cwd();
const root = cwd.endsWith("/scripts") ? join(cwd, "..") : cwd;
const read = (path: string) => readFileSync(join(root, path), "utf8");
const failures: string[] = [];
const must = (condition: boolean, message: string) => { if (!condition) failures.push(message); };
const authMode = read("artifacts/veroxa/src/lib/auth/authMode.ts");
const pilotAccess = read("artifacts/veroxa/src/lib/auth/pilotAccessAccounts.ts");
const app = read("artifacts/veroxa/src/App.tsx");
const nav = read("artifacts/veroxa/src/lib/teamPortalNav.ts");
const page = read("artifacts/veroxa/src/pages/team-momo-media-content.tsx");
const model = read("artifacts/veroxa/src/lib/momoMediaContent/momoMediaContentInventory.ts");
const controlCenter = read("artifacts/veroxa/src/pages/team-control-center.tsx");
const prepPage = read("artifacts/veroxa/src/pages/team-momo-pilot-prep.tsx");
const truthPage = read("artifacts/veroxa/src/pages/team-momo-business-truth.tsx");
const pkg = read("package.json");
const scriptsPkg = read("scripts/package.json");
const docs = ["artifacts/veroxa/docs/MOMO_MEDIA_CONTENT_INVENTORY_PACK.md", "artifacts/veroxa/docs/ACTIVE_DOCS_INDEX.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_PR_SEQUENCE.md", "artifacts/veroxa/docs/VEROXA_LOCKED_OPERATING_MEMORY.md", "artifacts/veroxa/docs/CURRENT_BUILD_STATUS.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_ARCHITECTURE.md", "artifacts/veroxa/docs/MOMO_INTERNAL_PILOT_PREP_PACK.md", "artifacts/veroxa/docs/MOMO_BUSINESS_TRUTH_REVIEW_PACK.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MEDIA_UPLOAD_STORAGE.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_AI_DRAFT_PREPARATION.md", "artifacts/veroxa/docs/ROUTE_PAGE_INVENTORY.md", "artifacts/veroxa/docs/VEROXA_ROUTE_SURFACE_MAP.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MOMO_READINESS_GATE.md", "artifacts/veroxa/docs/LIVE_AUTOMATION_V1_MOMO_ACTIVATION_GATE.md"].map(read).join("\n");
must(/AUTH_MODE\s*:\s*AuthMode\s*=\s*["']placeholder["']/.test(authMode), "AUTH_MODE must remain placeholder.");
must(pilotAccess.includes("/api/pilot-access"), "/api/pilot-access must remain active.");
must(app.includes('path="/team/momo-media-content"'), "Team route exists.");
const start = app.indexOf('path="/team/momo-media-content"');
const end = app.indexOf('path="/team/momo-activation-gate"');
const block = app.slice(start, end > start ? end : undefined);
must(block.includes('<InternalDemoGuard role="team">'), "Route guarded by InternalDemoGuard role=team.");
must(block.includes('<RealPortalDataBoundary portal="team">'), "Route wrapped in RealPortalDataBoundary portal=team.");
must(nav.includes("Momo Media") && nav.includes("/team/momo-media-content"), "Team nav includes Momo Media.");
must(controlCenter.includes("Momo Media + Content") && controlCenter.includes("PR #116") && controlCenter.includes("/team/momo-media-content"), "Control Center links to route.");
must(prepPage.includes("Review media/content inventory internally") && prepPage.includes("/team/momo-media-content"), "Momo Prep links safely.");
must(truthPage.includes("Review media rights and missing content") && truthPage.includes("/team/momo-media-content"), "Momo Business Truth links safely.");
must(!app.includes('path="/client/momo-media-content"'), "No client route exists.");
must(!existsSync(join(root, "artifacts/veroxa/src/pages/client-momo-media-content.tsx")), "No client page exists.");
must(!/path=["']\/team\/.*owner.*walkthrough/i.test(app), "No owner walkthrough route exists.");
must(!/role\s*===\s*["'](owner|operator|admin|super_admin|execution)["']/.test([app, nav, page, model].join("\n")), "No new roles beyond client/team.");
for (const phrase of ["Internal media/content inventory only.", "This does not activate the pilot.", "This does not turn on real auth.", "This does not create credentials.", "This does not contact Momo’s House.", "This does not upload, create, seed, or fake media.", "This does not publish externally.", "This does not connect Google, Meta, Yelp, TikTok, or delivery platforms.", "Media usage rights require owner confirmation before public use.", "Business-truth changes still require owner confirmation.", "AI may use only confirmed business truth and permissioned media in later internal drafts.", "Momo owner walkthrough remains blocked.", "No next activation PR is approved by default.", "Future real-world activation requires separate explicit Faraz approval."]) must(page.includes(phrase), `Page missing required safety copy: ${phrase}`);
for (const category of ["Core Food Photos", "Short Videos", "Logo / Brand Assets", "Storefront / Interior", "Behind The Scenes", "International Snacks / Drinks", "Content Pillars", "AI Drafting Rules", "Media Usage Rights", "Missing Media", "Future Confirmation Questions", "Safe Internal Next Decision"]) must(model.includes(category), `Model missing category: ${category}`);
for (const pillar of ["Momo Cravings", "First-Time Education", "Behind The Scenes", "Customer / Reaction Content", "Snack Discovery"]) must(model.includes(pillar), `Missing pillar: ${pillar}`);
must(!/\.insert\(|\.update\(|\.upsert\(|\.delete\(/.test([page, model].join("\n")), "No DB writes in media/content code.");
must(!readdirSync(join(root, "artifacts/veroxa")).includes("supabase"), "No database migration folder added under artifacts/veroxa.");
const activeCode = [app, nav, page, model, controlCenter, prepPage, truthPage].join("\n");
for (const pattern of [/go live now/i, /pilot activated/i, /owner walkthrough can begin/i, /activation approved/i, /real auth activation approved/i, /service_role/i, /platform token/i, /\.insert\(/, /\.update\(/, /\.upsert\(/, /\.delete\(/]) must(!pattern.test(activeCode), `Forbidden active-code pattern found: ${pattern}`);
for (const marker of ["GitHub PR #116", "Momo Media + Content Inventory Pack", "internal media/content inventory only", "AUTH_MODE remains placeholder", "/api/pilot-access remains active", "Momo owner walkthrough remains blocked", "No next activation PR is approved by default", "Future real-world activation requires separate explicit Faraz approval"]) must(docs.includes(marker), `Docs missing ${marker}.`);
must(docs.includes("MOMO_MEDIA_CONTENT_INVENTORY_PACK.md"), "Active Docs Index lists media pack.");
must(docs.includes("MOMO_BUSINESS_TRUTH_REVIEW_PACK.md"), "Active Docs Index lists business truth pack.");
must(scriptsPkg.includes("check-momo-media-content-inventory-pack"), "scripts package wires guardrail.");
must(pkg.includes("check-momo-media-content-inventory-pack"), "root verify:veroxa wires guardrail.");
if (failures.length) { console.error(failures.map((f) => `- ${f}`).join("\n")); process.exit(1); }
console.log("Momo Media + Content Inventory Pack guardrail passed.");
