export type MomoGrowthEvidence = {
  key: string;
  area: "google_business" | "reviews" | "meta" | "media" | "seo" | "tracking" | "claims" | "experiments";
  title: string;
  publisher: string;
  url: string;
  retrievedOn: "2026-07-16";
  productRequirement: string;
  guardrails: string[];
};

export const MOMO_GROWTH_EVIDENCE: readonly MomoGrowthEvidence[] = [
  {
    key: "google_local_ranking_factors",
    area: "google_business",
    title: "Tips to improve your local ranking on Google",
    publisher: "Google Business Profile Help",
    url: "https://support.google.com/business/answer/7091?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Track profile completeness, accuracy, current hours, photos, and review-response work as controllable inputs.",
    guardrails: ["Never promise rankings", "Never imply payment improves local rank", "Keep distance outside Veroxa scoring"],
  },
  {
    key: "google_business_representation",
    area: "google_business",
    title: "Guidelines for representing your business on Google",
    publisher: "Google Business Profile Help",
    url: "https://support.google.com/business/answer/3038177?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Require canonical business name, address, category, regular and special hours, menu details, descriptions, and real prices.",
    guardrails: ["Use real-world business information", "Separate regular and special hours", "Block zero-price menu publication"],
  },
  {
    key: "google_api_specific_consent",
    area: "google_business",
    title: "Google Business Profile API policies",
    publisher: "Google for Developers",
    url: "https://developers.google.com/my-business/content/policies",
    retrievedOn: "2026-07-16",
    productRequirement: "Persist prior specific express consent for each action or clearly bounded batch, notify clients of changes, and enforce cache expiry and disconnect controls.",
    guardrails: ["No silent listing edits", "No silent review replies", "No shared credentials", "Cache API content no longer than 30 days"],
  },
  {
    key: "google_owner_manager_access",
    area: "google_business",
    title: "Manage owners and managers of your Business Profile",
    publisher: "Google Business Profile Help",
    url: "https://support.google.com/business/answer/3403100?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Keep Momo as owner or co-owner and request manager access for a separate Veroxa account.",
    guardrails: ["Never request the owner's password", "Preserve owner control", "Support prompt access removal"],
  },
  {
    key: "google_photo_quality",
    area: "media",
    title: "Add photos or videos to your Business Profile",
    publisher: "Google Business Profile Help",
    url: "https://support.google.com/business/answer/6123536?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Add a Google Business 720×720 preset and quality checks for focus, lighting, truthful representation, JPG/PNG format, and limited alteration.",
    guardrails: ["Preserve originals", "Reject synthetic restaurant or food representation", "Label rehearsal fixtures as synthetic"],
  },
  {
    key: "google_review_policy",
    area: "reviews",
    title: "Prohibited and restricted content",
    publisher: "Google Maps User Contributed Content Policy",
    url: "https://support.google.com/business/answer/7400114?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Make review requests neutral and keep response drafts subject to an exact Momo decision.",
    guardrails: ["No incentives", "No review gating", "No selective positive requests", "No fake reviews"],
  },
  {
    key: "ftc_reviews_rule",
    area: "reviews",
    title: "Consumer Reviews and Testimonials Rule: Questions and Answers",
    publisher: "U.S. Federal Trade Commission",
    url: "https://www.ftc.gov/business-guidance/resources/consumer-reviews-testimonials-rule-questions-answers",
    retrievedOn: "2026-07-16",
    productRequirement: "Block fabricated testimonials, undisclosed incentives, and sentiment-conditioned review solicitation.",
    guardrails: ["No generated customer testimonials", "No purchased reviews", "Retain evidence for any endorsement claim"],
  },
  {
    key: "meta_instagram_publishing",
    area: "meta",
    title: "Instagram API with Instagram Login: Content Publishing",
    publisher: "Meta for Developers",
    url: "https://developers.facebook.com/documentation/instagram-platform/content-publishing",
    retrievedOn: "2026-07-16",
    productRequirement: "Prepare professional-account and Page preflight, immutable container payloads, status checks, publish receipts, idempotency, bounded retry, and quota monitoring.",
    guardrails: ["No credential assumptions", "No published claim without a receipt and read-back", "Keep live adapter disabled until access exists"],
  },
  {
    key: "meta_placement_formats",
    area: "media",
    title: "Best practices for aspect ratios across placements",
    publisher: "Meta Business Help Center",
    url: "https://www.facebook.com/business/help/103816146375741",
    retrievedOn: "2026-07-16",
    productRequirement: "Render 1:1 and 4:5 feed assets plus 9:16 Story/Reel assets with safe-zone preview.",
    guardrails: ["Do not stretch crops", "Preserve source lineage", "Keep platform presets versioned"],
  },
  {
    key: "instagram_alt_text",
    area: "media",
    title: "Edit the alternative text for a post on Instagram",
    publisher: "Instagram Help Center",
    url: "https://www.facebook.com/help/instagram/503708446705527",
    retrievedOn: "2026-07-16",
    productRequirement: "Require useful alt text for image derivatives and media placements.",
    guardrails: ["Describe meaningful visual content", "Do not keyword-stuff alt text"],
  },
  {
    key: "w3c_media_captions",
    area: "media",
    title: "Captions/Subtitles",
    publisher: "W3C Web Accessibility Initiative",
    url: "https://www.w3.org/WAI/media/av/captions/",
    retrievedOn: "2026-07-16",
    productRequirement: "Require reviewed captions or transcripts before video is considered publication-ready.",
    guardrails: ["Video remains intake-only until caption and editing QA exist", "Keep human review for speech accuracy"],
  },
  {
    key: "google_people_first_content",
    area: "seo",
    title: "Creating helpful, reliable, people-first content",
    publisher: "Google Search Central",
    url: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    retrievedOn: "2026-07-16",
    productRequirement: "Evaluate whether page and social copy helps real diners and is accurate, original, and locally relevant.",
    guardrails: ["No scaled low-value pages", "No unsupported experience or expertise claims", "Generated drafts require factual review"],
  },
  {
    key: "google_title_links",
    area: "seo",
    title: "Influencing your title links in search results",
    publisher: "Google Search Central",
    url: "https://developers.google.com/search/docs/appearance/title-link",
    retrievedOn: "2026-07-16",
    productRequirement: "Draft unique, concise, descriptive titles and detect keyword stuffing and repeated boilerplate.",
    guardrails: ["No unsupported superlatives", "Do not guarantee the displayed title", "Keep before/after and rollback snapshots"],
  },
  {
    key: "google_local_business_schema",
    area: "seo",
    title: "Local business structured data",
    publisher: "Google Search Central",
    url: "https://developers.google.com/search/docs/appearance/structured-data/local-business",
    retrievedOn: "2026-07-16",
    productRequirement: "Generate Restaurant JSON-LD only from confirmed visible facts and validate it before deployment.",
    guardrails: ["No self-serving review markup", "Do not publish conflicting hours", "Structured data must match page content"],
  },
  {
    key: "google_campaign_tagging",
    area: "tracking",
    title: "URL builders: Collect campaign data with custom URLs",
    publisher: "Google Analytics Help",
    url: "https://support.google.com/analytics/answer/10917952?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Persist normalized UTM source, medium, campaign, and content mappings to each approved item and receipt.",
    guardrails: ["No PII in campaign parameters", "Keep source-of-truth IDs immutable", "Treat missing metrics as missing"],
  },
  {
    key: "google_analytics_pii",
    area: "tracking",
    title: "Avoid sending personally identifiable information",
    publisher: "Google Analytics Help",
    url: "https://support.google.com/analytics/answer/6366371?hl=en",
    retrievedOn: "2026-07-16",
    productRequirement: "Lint tracking parameters and analytics payloads for email addresses, phone numbers, names, and other direct identifiers.",
    guardrails: ["Block PII before URL generation", "Do not copy client contact data into metrics"],
  },
  {
    key: "ftc_truthful_advertising",
    area: "claims",
    title: "Advertising and Marketing Basics",
    publisher: "U.S. Federal Trade Commission",
    url: "https://www.ftc.gov/business-guidance/advertising-marketing",
    retrievedOn: "2026-07-16",
    productRequirement: "Require support for ranking, freshness, ingredient-source, dietary, health, popularity, award, price, and offer claims.",
    guardrails: ["Claims must be truthful and non-deceptive", "Retain substantiation", "Owner confirmation alone does not prove an objective ranking claim"],
  },
  {
    key: "meta_ab_testing",
    area: "experiments",
    title: "About A/B tests",
    publisher: "Meta Business Help Center",
    url: "https://www.facebook.com/business/help/942567712892076",
    retrievedOn: "2026-07-16",
    productRequirement: "Pre-register one hypothesis, primary variable, metric, audience, and duration; distinguish randomized tests from observational comparisons.",
    guardrails: ["Do not change multiple variables in a single-variable test", "Do not claim causality from observational data", "No outcome forecast"],
  },
  {
    key: "copyright_media_rights",
    area: "media",
    title: "Copyright and Photography",
    publisher: "U.S. Copyright Office",
    url: "https://www.copyright.gov/engage/photographers/",
    retrievedOn: "2026-07-16",
    productRequirement: "Record ownership or permission, allowed channels, expiry, provenance, and revocation before editing, reuse, or publication.",
    guardrails: ["Preserve the original", "Block expired or revoked rights", "Keep historical usage records"],
  },
] as const;

export function momoGrowthEvidenceFor(area: MomoGrowthEvidence["area"]): readonly MomoGrowthEvidence[] {
  return MOMO_GROWTH_EVIDENCE.filter((item) => item.area === area);
}
