export type MomoBrandAiRuleStatus = "allowed_internal_rule" | "internal_strategy_only" | "requires_business_truth_confirmation" | "requires_media_rights_confirmation" | "requires_sensitive_claim_confirmation" | "blocked_for_public_use" | "team_review_required" | "future_step_required";
export type MomoBrandAiRuleRisk = "low" | "medium" | "high" | "critical";
export type MomoBrandAiRuleCategory = "Brand Voice Foundation" | "Approved Tone" | "Unsafe Tone" | "Content Pillar Prompt Rules" | "Caption Drafting Rules" | "Local SEO Rules" | "Sensitive Claim Rules" | "Media Dependency Rules" | "Business Truth Dependency Rules" | "AI Forbidden Outputs" | "Prompt Template Boundaries" | "Team Review Requirements" | "Future Confirmation Questions" | "Safe Internal Next Decision";

export type MomoBrandAiRuleItem = { id: string; category: MomoBrandAiRuleCategory; title: string; status: MomoBrandAiRuleStatus; risk: MomoBrandAiRuleRisk; description: string; allowed_ai_behavior: string; blocked_ai_behavior: string; required_confirmation: string; safe_internal_next_step: string; route_href?: string };

export const MOMO_BRAND_AI_ROUTE = "/team/momo-brand-ai-rules";
export const MOMO_BRAND_AI_CATEGORIES: MomoBrandAiRuleCategory[] = ["Brand Voice Foundation", "Approved Tone", "Unsafe Tone", "Content Pillar Prompt Rules", "Caption Drafting Rules", "Local SEO Rules", "Sensitive Claim Rules", "Media Dependency Rules", "Business Truth Dependency Rules", "AI Forbidden Outputs", "Prompt Template Boundaries", "Team Review Requirements", "Future Confirmation Questions", "Safe Internal Next Decision"];
export const MOMO_BRAND_AI_ALLOWED_TEAM_LINKS = ["/team/momo-media-content", "/team/momo-business-truth", "/team/momo-pilot-prep", "/team/momo-live-readiness", "/team/momo-activation-gate", "/team/control-center", "/team/profile-corrections", "/team/upload-inbox", "/team/messages", "/team/activity-log", "/team/ai-drafts", "/team/reports-from-activity"];

const base = { required_confirmation: "Owner/business-truth/media-rights confirmation is required before customer-visible use.", safe_internal_next_step: "Keep as internal guidance for Team/Faraz review; no external action from this PR." };

export const MOMO_BRAND_AI_RULE_ITEMS: MomoBrandAiRuleItem[] = [
  { id: "brand-voice-foundation", category: "Brand Voice Foundation", title: "Internal Momo draft voice", status: "internal_strategy_only", risk: "medium", description: "Warm, simple, crave-focused, local, approachable, first-timer friendly, food-forward, not corporate, not hype/fake-growth focused, not overpromising, and not using unconfirmed facts.", allowed_ai_behavior: "Later internal drafts may follow this voice only after truth and media dependencies are checked.", blocked_ai_behavior: "Do not treat voice direction as owner-approved or public/customer-visible copy.", ...base },
  { id: "approved-tone", category: "Approved Tone", title: "Allowed internal tone directions", status: "allowed_internal_rule", risk: "medium", description: "Craving, comfort food, try momos for the first time, sauce/dip focus, local momo spot, simple, friendly, helpful, short social captions, educational but not lecture-style, inviting without pressure.", allowed_ai_behavior: "Use these only in later internal drafts after confirmed business truth and permissioned media are available.", blocked_ai_behavior: "Do not combine friendly tone with unconfirmed facts, pressure, guarantees, or customer-visible output.", ...base },
  { id: "unsafe-tone", category: "Unsafe Tone", title: "Blocked tone and claims", status: "blocked_for_public_use", risk: "critical", description: "Fake urgency/scarcity/discounts, guaranteed best in city, guaranteed authentic unless confirmed, health or halal/dietary claims unless confirmed, fake customer reviews, fake popularity/rankings, exaggerated promises, aggressive sales language, offensive jokes, and owner/staff/family claims without confirmation are blocked.", allowed_ai_behavior: "Flag unsafe tone as blocked guidance.", blocked_ai_behavior: "Do not include unsafe tone in any future draft or public/customer-visible use.", ...base },
  ...["Momo Cravings", "First-Time Education", "Behind The Scenes", "Customer / Reaction Content", "Snack Discovery", "Local SEO / Momo spot positioning", "Sauce / spice / pairing content"].map((pillar) => ({ id: `pillar-${pillar.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`, category: "Content Pillar Prompt Rules" as const, title: pillar, status: "team_review_required" as const, risk: pillar.includes("Customer") || pillar.includes("Behind") ? "high" as const : "medium" as const, description: `Internal prompt boundary for ${pillar}: AI may later prepare draft structure only after the dish/item, business context, and media shown are confirmed.`, allowed_ai_behavior: "Draft internal-only outlines tied to verified facts, available permissioned media, and Team review status.", blocked_ai_behavior: "Do not invent menu items, availability, owner stories, customer reactions, exact neighborhoods, prices, offers, claims, or media context.", required_confirmation: "Business truth, media usage rights, and staff/customer consent where relevant.", safe_internal_next_step: "Compare this pillar against business-truth review and media/content inventory before any later internal drafting.", route_href: pillar.includes("Media") ? "/team/momo-media-content" : undefined })),
  { id: "caption-rules", category: "Caption Drafting Rules", title: "Future caption constraints", status: "team_review_required", risk: "high", description: "Keep short and simple; do not mention prices, hours, promotions, delivery/catering, halal/dietary claims, popularity, rankings, or results unless confirmed; draft-only / Team review required; no automatic publication.", allowed_ai_behavior: "Later internal captions may be marked draft-only and routed for Team/Faraz review.", blocked_ai_behavior: "No publish-ready or final customer-facing caption output.", ...base },
  { id: "local-seo-rules", category: "Local SEO Rules", title: "Local SEO language limits", status: "requires_business_truth_confirmation", risk: "high", description: "San Antonio language only if location is confirmed; momo spot can be internal positioning; neighborhood/near-me wording must not invent exact neighborhoods; best/top-rated/number one/most popular claims are blocked unless independently confirmed and approved; Google Business Profile updates remain future/manual/approval-gated.", allowed_ai_behavior: "Use verified location terms in internal drafts only.", blocked_ai_behavior: "Do not invent neighborhoods, rankings, platform access, or active Google updates.", ...base },
  { id: "sensitive-claims", category: "Sensitive Claim Rules", title: "Sensitive claims blocked until owner-confirmed", status: "requires_sensitive_claim_confirmation", risk: "critical", description: "Halal, vegetarian/vegan, allergen-free, gluten-free, health claims, authentic/origin claims, family-owned, awards/certifications, religious/cultural claims, ownership background, and staff/customer identity claims are blocked until owner-confirmed.", allowed_ai_behavior: "Ask Team to verify claim status internally.", blocked_ai_behavior: "Do not draft sensitive claims as facts.", ...base },
  { id: "media-dependencies", category: "Media Dependency Rules", title: "Permissioned media required", status: "requires_media_rights_confirmation", risk: "critical", description: "AI may only draft around media later if media exists, rights are confirmed, staff/customer consent is confirmed if faces appear, shown dishes are available, media is not misleading, media is not generated/fake, and Team approval is required.", allowed_ai_behavior: "Reference media only as internal context after permission and accuracy checks.", blocked_ai_behavior: "Do not describe missing, fake, generated, misleading, or unpermissioned media as usable.", ...base, route_href: "/team/momo-media-content" },
  { id: "business-truth-dependencies", category: "Business Truth Dependency Rules", title: "Confirmed facts only", status: "requires_business_truth_confirmation", risk: "critical", description: "AI may only reference confirmed menu items, prices if used, hours if used, address/phone/order links if used, delivery/catering status if used, confirmed claims, and confirmed platform access. Unconfirmed facts are blocked or internal-only.", allowed_ai_behavior: "Use confirmed business truth only in later internal drafts.", blocked_ai_behavior: "Do not invent or imply facts not confirmed.", ...base, route_href: "/team/momo-business-truth" },
  { id: "ai-forbidden-outputs", category: "AI Forbidden Outputs", title: "Forbidden future AI outputs", status: "blocked_for_public_use", risk: "critical", description: "Final customer-facing copy, publish-ready copy, direct owner outreach, public replies, fake reviews/testimonials/metrics/media descriptions, invented menu/prices/offers/hours, platform sync instructions as active, go-live/post-now instructions, real-auth setup instructions, credentials, and secrets are forbidden.", allowed_ai_behavior: "Return internal draft boundaries only when a later approved AI workflow exists.", blocked_ai_behavior: "Do not output final, external, credentialed, or action-triggering content.", ...base },
  { id: "prompt-template-boundaries", category: "Prompt Template Boundaries", title: "Static prompt-template sections only", status: "internal_strategy_only", risk: "high", description: "Allowed template sections: system intent, context inputs required, business-truth checks, media-rights checks, blocked claims, output format for internal draft, Team review reminder, and no-publication reminder. No executable AI calls, SDKs, runtime endpoints, env vars, or key handling.", allowed_ai_behavior: "Use as static design guidance only.", blocked_ai_behavior: "Do not store prompts as jobs or add provider/runtime behavior.", ...base },
  { id: "team-review", category: "Team Review Requirements", title: "Team/Faraz review required", status: "team_review_required", risk: "critical", description: "Every future AI output must be internal-only, draft status, reviewed by Team/Faraz, checked against business truth and media rights, blocked if sensitive claims are unconfirmed or customer-visible action would result, never auto-approved, and never auto-published.", allowed_ai_behavior: "Label future outputs as internal draft only after a separate approved workflow exists.", blocked_ai_behavior: "No automatic approval or publication.", ...base },
  { id: "future-questions", category: "Future Confirmation Questions", title: "Future owner-confirmation questions", status: "future_step_required", risk: "medium", description: "Internal future questions: preferred tone, emphasized menu items, items not to promote, approved claims, publicly usable media, staff/customer face permission, snack/drink availability, and accurate local positioning. This is not outreach.", allowed_ai_behavior: "Help Team organize future questions internally.", blocked_ai_behavior: "Do not contact the owner or create an outreach flow.", ...base },
  { id: "safe-next-decision", category: "Safe Internal Next Decision", title: "Faraz reviews rules before any later AI work", status: "future_step_required", risk: "high", description: "Faraz reviews brand/AI rules; Team decides which rules are safe for later AI draft generation; block real AI generation until prompt rules, business truth, and media rights are ready. No external action and no next activation PR is approved by default.", allowed_ai_behavior: "Keep this as internal decision support.", blocked_ai_behavior: "Do not infer activation, readiness, contact, or customer-visible use.", ...base, route_href: "/team/control-center" },
];
