export type MomoBusinessTruthStatus = "owner_confirmed" | "internally_known_only" | "prefilled_unconfirmed" | "needs_owner_confirmation" | "needs_faraz_review" | "unsafe_for_public_use" | "blocked" | "future_step_required";
export type MomoBusinessTruthRisk = "low" | "medium" | "high" | "critical";
export type MomoBusinessTruthCategory = "Core Restaurant Identity" | "Menu / Ordering Truth" | "Brand / Positioning Truth" | "Sensitive Claims" | "Access / Platform Truth" | "Media Truth" | "Confirmation Script Draft" | "Business Truth Blockers" | "Safe Internal Next Decision";

export interface MomoBusinessTruthReviewItem {
  id: string;
  category: MomoBusinessTruthCategory;
  label: string;
  current_value: string;
  status: MomoBusinessTruthStatus;
  risk: MomoBusinessTruthRisk;
  source_note: string;
  public_use_rule: string;
  owner_confirmation_question: string;
  safe_internal_next_step: string;
  route_href?: string;
}

export const MOMO_BUSINESS_TRUTH_CATEGORIES: MomoBusinessTruthCategory[] = ["Core Restaurant Identity", "Menu / Ordering Truth", "Brand / Positioning Truth", "Sensitive Claims", "Access / Platform Truth", "Media Truth", "Confirmation Script Draft", "Business Truth Blockers", "Safe Internal Next Decision"];

const noPublicUse = "Internal review only; do not use publicly until owner confirmation and Veroxa/Faraz approval.";

export const MOMO_BUSINESS_TRUTH_REVIEW_ITEMS: MomoBusinessTruthReviewItem[] = [
  { id: "identity-display-name", category: "Core Restaurant Identity", label: "Restaurant display name", current_value: "Momo's House / Momo House San Antonio appears in internal pilot context.", status: "prefilled_unconfirmed", risk: "medium", source_note: "Static prep docs reference Momo's House but do not make this a fresh owner-confirmed source.", public_use_rule: noPublicUse, owner_confirmation_question: "What exact restaurant display name should Veroxa use if a future owner-confirmation step is separately approved?", safe_internal_next_step: "Keep as prefilled internal context only.", route_href: "/team/momo-pilot-prep" },
  { id: "identity-legal-name", category: "Core Restaurant Identity", label: "Legal/business name if different", current_value: "Unknown.", status: "needs_owner_confirmation", risk: "high", source_note: "No safe owner-confirmed legal name source is present in current docs.", public_use_rule: noPublicUse, owner_confirmation_question: "Is there a legal or business name different from the public display name?", safe_internal_next_step: "Leave blank in public materials." },
  { id: "identity-address", category: "Core Restaurant Identity", label: "Address", current_value: "Prefilled from earlier internal Momo work where available, but not owner-confirmed for public use by this PR.", status: "prefilled_unconfirmed", risk: "high", source_note: "Address is business-truth and requires confirmation before customer-visible use.", public_use_rule: noPublicUse, owner_confirmation_question: "What is the exact public address and any suite/unit formatting?", safe_internal_next_step: "Review internally without publishing.", route_href: "/team/profile-corrections" },
  { id: "identity-phone", category: "Core Restaurant Identity", label: "Phone", current_value: "Prefilled if present in internal profile context; unconfirmed for public use.", status: "prefilled_unconfirmed", risk: "high", source_note: "Phone number affects customer contact and must be confirmed.", public_use_rule: noPublicUse, owner_confirmation_question: "What phone number should customers use?", safe_internal_next_step: "Keep in needs-confirmation queue." },
  { id: "identity-hours", category: "Core Restaurant Identity", label: "Business hours", current_value: "Unconfirmed.", status: "needs_owner_confirmation", risk: "critical", source_note: "Hours and holiday hours are business-truth fields.", public_use_rule: noPublicUse, owner_confirmation_question: "What are current regular and holiday hours?", safe_internal_next_step: "Block any public schedule wording." },
  { id: "identity-website", category: "Core Restaurant Identity", label: "Website/domain", current_value: "Unconfirmed website/domain state.", status: "needs_owner_confirmation", risk: "high", source_note: "Website and domain links can misdirect customers if wrong.", public_use_rule: noPublicUse, owner_confirmation_question: "What website, ordering, and domain links should Veroxa treat as official?", safe_internal_next_step: "Compare internally only.", route_href: "/team/profile-corrections" },
  { id: "identity-primary-contact", category: "Core Restaurant Identity", label: "Primary contact info", current_value: "Unknown for owner-confirmation purposes.", status: "blocked", risk: "critical", source_note: "This PR must not create outreach or credentials.", public_use_rule: "Not for public use; no outreach from this PR.", owner_confirmation_question: "Who is the approved owner/contact if Faraz separately approves a future confirmation plan?", safe_internal_next_step: "Wait for separate Faraz approval before any external step." },
  ...["Menu items", "Prices", "Momo styles", "Meat/veg options", "Sauces", "Specials/promotions", "Ordering links", "Delivery/catering status"].map((label, index) => ({ id: `menu-${index}`, category: "Menu / Ordering Truth" as const, label, current_value: "Prefilled or unknown internal context only.", status: "needs_owner_confirmation" as const, risk: label === "Prices" || label.includes("links") ? "critical" as const : "high" as const, source_note: "Menu/order details can change and no current owner-confirmed source is established by this PR.", public_use_rule: "Do not publish or use publicly without owner confirmation.", owner_confirmation_question: `What is the current truth for ${label.toLowerCase()}?`, safe_internal_next_step: "Keep in business-truth blocker list." })),
  ...["Cuisine identity", "Momo spot / niche-craving positioning", "Family-friendly tone", "Local San Antonio positioning", "First-time momo education", "Snack/drink secondary content"].map((label, index) => ({ id: `brand-${index}`, category: "Brand / Positioning Truth" as const, label, current_value: "Internal strategy hypothesis only.", status: "internally_known_only" as const, risk: "medium" as const, source_note: "Useful for Team planning, not a public claim from this PR.", public_use_rule: "Safe only as internal strategy until owner confirmation.", owner_confirmation_question: `Does this positioning feel accurate for Momo's House: ${label}?`, safe_internal_next_step: "Use for internal review framing only." })),
  ...["Halal", "Dietary/allergen claims", "Ownership/family-owned claims", "Awards/certifications", "Authenticity/origin claims", "Health claims"].map((label, index) => ({ id: `sensitive-${index}`, category: "Sensitive Claims" as const, label, current_value: "Not verified for public use.", status: "blocked" as const, risk: "critical" as const, source_note: "Sensitive claims require owner-confirmed evidence before use.", public_use_rule: "Blocked unless owner-confirmed.", owner_confirmation_question: `Can the owner verify the exact ${label.toLowerCase()} language and proof?`, safe_internal_next_step: "Do not draft public claim language." })),
  ...["Google Business Profile ownership/access", "Meta Business Suite / Business Portfolio access", "Instagram/Facebook ownership", "Website/domain/email access", "Delivery platform access"].map((label, index) => ({ id: `access-${index}`, category: "Access / Platform Truth" as const, label, current_value: "Access state unknown or unconnected.", status: "future_step_required" as const, risk: "high" as const, source_note: "This PR is checklist-only and handles no connection or token flow.", public_use_rule: "Checklist only; no connection or token handling.", owner_confirmation_question: `Who controls ${label.toLowerCase()} and what access path is approved later?`, safe_internal_next_step: "Document as dependency only." })),
  ...["Existing food photos", "Existing short videos", "Logo", "Storefront/interior photos", "Behind-the-scenes/prep visuals", "International snack/drink visuals"].map((label, index) => ({ id: `media-${index}`, category: "Media Truth" as const, label, current_value: "Media availability/rights unconfirmed.", status: "needs_owner_confirmation" as const, risk: "high" as const, source_note: "Media can only be used publicly with rights and approval.", public_use_rule: "Media usage rights and owner confirmation required before public use.", owner_confirmation_question: `May Veroxa use ${label.toLowerCase()} publicly, and who owns the media?`, safe_internal_next_step: "Track as media dependency.", route_href: "/team/upload-inbox" })),
  { id: "script-future-questions", category: "Confirmation Script Draft", label: "Future owner-confirmation questions", current_value: "Draft questions only for a separately approved future step.", status: "future_step_required", risk: "medium", source_note: "This is not an outreach flow and does not say to contact owner now.", public_use_rule: "Internal-only planning; no external use from this PR.", owner_confirmation_question: "If Faraz approves later, ask owner to verify identity, hours, menu, prices, links, claims, access, and media rights.", safe_internal_next_step: "Faraz reviews wording internally." },
  { id: "blockers-public-use", category: "Business Truth Blockers", label: "Blockers preventing public use", current_value: "Unconfirmed price/menu/hour/claim/link fields, missing access, missing media usage rights, and no owner-confirmed source.", status: "blocked", risk: "critical", source_note: "These blockers prevent public/customer-visible action.", public_use_rule: "Public use is blocked.", owner_confirmation_question: "Which facts can the owner confirm with exact current details?", safe_internal_next_step: "Keep blocked until separate approval and confirmation." },
  { id: "decision-safe-next", category: "Safe Internal Next Decision", label: "Safe internal next decision", current_value: "Faraz reviews internal truth map, decides whether to keep researching internally, and decides whether a future owner-confirmation plan is needed.", status: "needs_faraz_review", risk: "low", source_note: "No external action from this PR and no next activation PR approved by default.", public_use_rule: "Internal Team decision support only.", owner_confirmation_question: "No owner question unless Faraz separately approves a future plan.", safe_internal_next_step: "Review internally; do not trigger activation or outreach." },
];

export const MOMO_BUSINESS_TRUTH_ALLOWED_TEAM_LINKS = ["/team/momo-pilot-prep", "/team/momo-live-readiness", "/team/momo-activation-gate", "/team/control-center", "/team/profile-corrections", "/team/upload-inbox", "/team/messages", "/team/activity-log", "/team/ai-drafts", "/team/reports-from-activity"];
