import type { MediaAssetInsight } from "./types";
export const mediaIntelligenceSeedData: MediaAssetInsight[] = [
  {
    id: "media-best-seller",
    clientId: "demo-c",
    restaurantName: "Growth media-ready benchmark",
    mediaType: "photo",
    category: "best_seller",
    platformFit: ["google", "facebook", "instagram"],
    qualityStatus: "ready",
    performanceStatus: "promising",
    reachContribution: "medium",
    actionContribution: "unknown",
    bestUse: "Use as best-seller visibility photo after team review.",
    clientSafeSummary: "This type of media is easier for Veroxa to use.",
    teamNotes:
      "Strong food closeup; good for Google and Instagram. Not live analytics.",
    nextRecommendation: "Ask for 3 more clear best-seller closeups.",
    warnings: [],
  },
  {
    id: "media-prep-video",
    clientId: "demo-c",
    restaurantName: "Growth media-ready benchmark",
    mediaType: "video",
    category: "food_prep",
    platformFit: ["instagram", "reels", "tiktok"],
    qualityStatus: "usable",
    performanceStatus: "promising",
    reachContribution: "medium",
    actionContribution: "unknown",
    bestUse: "Save for video-support plan path and team review.",
    clientSafeSummary:
      "Short food-prep videos are useful if your plan includes video support.",
    teamNotes: "Growth/Premium can use Reels/TikTok paths; Starter cannot.",
    nextRecommendation: "Confirm item name before public caption.",
    warnings: ["needs business-truth confirmation if item claim is implied"],
  },
  {
    id: "media-dark-photo",
    clientId: "demo-b",
    restaurantName: "Starter low-media benchmark",
    mediaType: "photo",
    category: "food_closeup",
    platformFit: ["save_for_later"],
    qualityStatus: "needs_better_lighting",
    performanceStatus: "weak",
    reachContribution: "low",
    actionContribution: "unknown",
    bestUse: "Save for later unless no better image exists.",
    clientSafeSummary: "This photo may need better lighting.",
    teamNotes: "Weak media; request replacement before using in public copy.",
    nextRecommendation:
      "Ask for brighter natural-light photo of the same item.",
    warnings: [],
  },
  {
    id: "media-menu-price",
    clientId: "demo-d",
    restaurantName: "Growth inconsistent-upload benchmark",
    mediaType: "menu_photo",
    category: "menu",
    platformFit: ["google", "report_only"],
    qualityStatus: "needs_confirmation",
    performanceStatus: "not_enough_data",
    reachContribution: "unknown",
    actionContribution: "unknown",
    bestUse: "Use only after client confirms menu details.",
    clientSafeSummary:
      "This item is saved for later until details are confirmed.",
    teamNotes:
      "Potential menu/price truth. Ask client before any public-facing update.",
    nextRecommendation: "Ask client to confirm menu names and visible details.",
    warnings: ["business truth confirmation required"],
  },
];
