import { buildPlatformDraftDirections } from "./mediaPlatformFit";
import type { MediaAssetInsight } from "./types";
export const mediaIntelligenceSeedData: MediaAssetInsight[] = [
  {
    id: "media-best-seller",
    clientId: "demo-c",
    restaurantName: "Complete Online Presence media-ready benchmark",
    mediaType: "photo",
    category: "best_seller",
    platformFit: ["facebook", "instagram", "google"],
    draftDirections: buildPlatformDraftDirections("photo", "best_seller"),
    qualityStatus: "ready",
    performanceStatus: "promising",
    reachContribution: "medium",
    actionContribution: "unknown",
    bestUse: "Use as a platform-specific image draft set after team review.",
    clientSafeSummary: "This clear best-seller photo is easier for Veroxa to use across current launch channels.",
    teamNotes: "Image media creates Facebook, Instagram, and Google Business Profile / Google update draft directions. No single-platform-only fit language.",
    nextRecommendation: "Ask for 3 more clear best-seller closeups with good lighting.",
    warnings: [],
  },
  {
    id: "media-prep-video",
    clientId: "demo-c",
    restaurantName: "Complete Online Presence media-ready benchmark",
    mediaType: "video",
    category: "food_prep",
    platformFit: ["facebook", "instagram_reels_coming_soon", "google", "tiktok_coming_soon"],
    draftDirections: buildPlatformDraftDirections("video", "food_prep"),
    qualityStatus: "usable",
    performanceStatus: "promising",
    reachContribution: "medium",
    actionContribution: "unknown",
    bestUse: "Create a video draft set for team/internal readiness while keeping Reels/TikTok marked coming soon.",
    clientSafeSummary: "Video support is coming soon; Veroxa can still note what media may help future channels.",
    teamNotes: "Video media creates Facebook, Instagram/Reels, Google, and TikTok draft directions; Reels/TikTok are client-not-included at launch.",
    nextRecommendation: "Confirm item name before any public caption or Google update draft.",
    warnings: ["Reels/TikTok coming soon", "business-truth confirmation may be required"],
  },
  {
    id: "media-dark-photo",
    clientId: "demo-b",
    restaurantName: "Complete Online Presence low-media benchmark",
    mediaType: "photo",
    category: "food_closeup",
    platformFit: ["facebook", "instagram", "google"],
    draftDirections: buildPlatformDraftDirections("photo", "food_closeup"),
    qualityStatus: "needs_better_lighting",
    performanceStatus: "weak",
    reachContribution: "low",
    actionContribution: "unknown",
    bestUse: "Save for later unless no better image exists; request better lighting.",
    clientSafeSummary: "This photo may need better lighting before consistent posting.",
    teamNotes: "Weak media can still be represented as a draft set, but team should ask for a brighter replacement.",
    nextRecommendation: "Ask for brighter natural-light photo of the same item.",
    warnings: [],
  },
  {
    id: "media-menu-price",
    clientId: "demo-d",
    restaurantName: "Complete Online Presence confirmation benchmark",
    mediaType: "menu_photo",
    category: "menu",
    platformFit: ["google", "facebook", "instagram", "report_only"],
    draftDirections: buildPlatformDraftDirections("menu_photo", "menu"),
    qualityStatus: "needs_confirmation",
    performanceStatus: "not_enough_data",
    reachContribution: "unknown",
    actionContribution: "unknown",
    bestUse: "Use only after client confirms menu details and business truth.",
    clientSafeSummary: "This item is saved for later until details are confirmed.",
    teamNotes: "Potential menu/price truth. Ask client before any public-facing update.",
    nextRecommendation: "Ask client to confirm menu names and visible details.",
    warnings: ["business truth confirmation required"],
  },
];
