import type { MediaAsset } from "../database/models";
import { MediaFileType, MediaSourceType, MediaQualityAIFlag, MediaReviewStatus } from "../database/enums";

// ── Demo media assets — Demo Grill House (id: mamadali) ──────────────────────
// All IDs become UUID primary keys in the real database.

export const mamadaliMediaAssets: MediaAsset[] = [
  {
    id: "media-mamadali-001",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/lamb-shoulder-hero.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/lamb-shoulder-hero.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Good lighting, food well-centred, no blur detected.",
    reviewStatus: MediaReviewStatus.approved,
    reviewedByUserId: "user-team-jordan",
    reviewedAt: "2026-05-20T10:30:00Z",
    usedInPostId: "post-mamadali-001",
    createdAt: "2026-05-18T09:00:00Z",
    updatedAt: "2026-05-20T10:30:00Z",
  },
  {
    id: "media-mamadali-002",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/family-feast-promo.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/family-feast-promo.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Bright, clean table setting. Strong for engagement.",
    reviewStatus: MediaReviewStatus.scheduled,
    reviewedByUserId: "user-team-jordan",
    reviewedAt: "2026-05-21T11:00:00Z",
    usedInPostId: "post-mamadali-002",
    createdAt: "2026-05-18T09:05:00Z",
    updatedAt: "2026-05-21T11:00:00Z",
  },
  {
    id: "media-mamadali-003",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.video,
    sourceType: MediaSourceType.team_upload,
    storageUrl: "demo://media/mamadali/kitchen-bts-reel.mp4",
    thumbnailUrl: "demo://media/mamadali/thumbs/kitchen-bts-reel.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Smooth motion, well-lit kitchen environment.",
    reviewStatus: MediaReviewStatus.approved,
    reviewedByUserId: "user-team-sarah",
    reviewedAt: "2026-05-22T09:15:00Z",
    usedInPostId: "post-mamadali-003",
    createdAt: "2026-05-19T14:00:00Z",
    updatedAt: "2026-05-22T09:15:00Z",
  },
  {
    id: "media-mamadali-004",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/mixed-grill-platter.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/mixed-grill-platter.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Excellent platter composition. High reach potential.",
    reviewStatus: MediaReviewStatus.used,
    reviewedByUserId: "user-team-jordan",
    reviewedAt: "2026-05-14T10:00:00Z",
    usedInPostId: "post-mamadali-004",
    createdAt: "2026-05-12T08:30:00Z",
    updatedAt: "2026-05-17T12:00:00Z",
  },
  {
    id: "media-mamadali-005",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.legacy_reuse,
    storageUrl: "demo://media/mamadali/google-review-highlight.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/google-review-highlight.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Review graphic. Clear text, brand-consistent.",
    reviewStatus: MediaReviewStatus.used,
    reviewedByUserId: "user-team-alex",
    reviewedAt: "2026-05-15T09:00:00Z",
    usedInPostId: "post-mamadali-005",
    createdAt: "2026-05-13T11:00:00Z",
    updatedAt: "2026-05-18T13:00:00Z",
  },
  {
    id: "media-mamadali-006",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.team_upload,
    storageUrl: "demo://media/mamadali/opening-hours-graphic.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/opening-hours-graphic.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Informational graphic, clear and on-brand.",
    reviewStatus: MediaReviewStatus.used,
    reviewedByUserId: "user-team-sarah",
    reviewedAt: "2026-05-16T10:30:00Z",
    usedInPostId: "post-mamadali-006",
    createdAt: "2026-05-14T10:00:00Z",
    updatedAt: "2026-05-19T14:00:00Z",
  },
  {
    id: "media-mamadali-007",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/prep-day-bts.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/prep-day-bts.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Authentic behind-the-scenes content. Strong reach signal.",
    reviewStatus: MediaReviewStatus.used,
    reviewedByUserId: "user-team-jordan",
    reviewedAt: "2026-05-17T09:00:00Z",
    usedInPostId: "post-mamadali-007",
    createdAt: "2026-05-15T08:00:00Z",
    updatedAt: "2026-05-20T11:00:00Z",
  },
  {
    id: "media-mamadali-008",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/aubergine-dip-new-menu.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/aubergine-dip-new-menu.jpg",
    aiQualityFlag: MediaQualityAIFlag.borderline,
    aiQualityNotes: "Slightly underexposed. Usable with brightness correction.",
    reviewStatus: MediaReviewStatus.team_review_pending,
    reviewedByUserId: null,
    reviewedAt: null,
    usedInPostId: null,
    createdAt: "2026-05-22T16:00:00Z",
    updatedAt: "2026-05-22T16:00:00Z",
  },
  {
    id: "media-mamadali-009",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.image,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/full-table-spread.jpg",
    thumbnailUrl: "demo://media/mamadali/thumbs/full-table-spread.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Wide shot of full table. Good for reach posts.",
    reviewStatus: MediaReviewStatus.usable,
    reviewedByUserId: "user-team-jordan",
    reviewedAt: "2026-05-23T08:00:00Z",
    usedInPostId: null,
    createdAt: "2026-05-22T17:00:00Z",
    updatedAt: "2026-05-23T08:00:00Z",
  },
  {
    id: "media-mamadali-010",
    clientId: "client-mamadali-001",
    fileType: MediaFileType.video,
    sourceType: MediaSourceType.client_upload,
    storageUrl: "demo://media/mamadali/chef-grilling-reel.mp4",
    thumbnailUrl: "demo://media/mamadali/thumbs/chef-grilling-reel.jpg",
    aiQualityFlag: MediaQualityAIFlag.likely_usable,
    aiQualityNotes: "Dynamic action shot on the grill. High engagement potential.",
    reviewStatus: MediaReviewStatus.shortlisted,
    reviewedByUserId: "user-team-sarah",
    reviewedAt: "2026-05-23T09:00:00Z",
    usedInPostId: null,
    createdAt: "2026-05-23T07:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];
