import type { RestaurantOnboardingProfile } from "./types";

const baseTruth = {
  hoursConfirmed: true,
  holidayHoursConfirmed: false,
  phoneConfirmed: true,
  addressConfirmed: true,
  menuItemsConfirmed: true,
  menuPricesMentioned: false,
  menuPricesConfirmed: false,
  existingOfferProvided: false,
  existingOfferConfirmed: false,
  cateringAvailabilityConfirmed: false,
  dietaryClaimsConfirmed: false,
  orderingReservationLinksConfirmed: true,
  futureAdsAcknowledged: false,
  futureReadinessAssessmentAcknowledged: false,
};

export const restaurantOnboardingSeedProfiles: RestaurantOnboardingProfile[] = [
  {
    clientId: "complete-presence-ready-benchmark",
    restaurantName: "Complete Online Presence ready benchmark",
    packageId: "complete_online_presence",
    contactName: "Owner contact",
    contactRole: "Owner",
    phone: "(555) 010-1000",
    email: "complete-presence-ready@example.com",
    address: "100 Preview Way, Sample City, ST",
    websiteUrl: "https://example.com/complete-presence-ready",
    googleBusinessProfileUrl: "https://business.google.com/example-complete-presence-ready",
    googleMapsUrl: "https://maps.google.com/example-complete-presence-ready",
    instagramUrl: "https://instagram.com/example_launch_ready",
    facebookUrl: "https://facebook.com/example-complete-presence-ready",
    tiktokUrl: "",
    menuUrl: "https://example.com/complete-presence-ready/menu",
    orderingUrl: "https://example.com/complete-presence-ready/order",
    reservationUrl: "",
    cateringUrl: "",
    cuisineType: "Casual comfort food",
    bestSellers: ["Signature plate", "Family platter", "Fresh bowl"],
    foodCategories: ["Entrees", "Sides", "Drinks"],
    customerTypes: ["Families", "Lunch regulars"],
    busyDays: ["Friday", "Saturday"],
    busyTimes: ["Lunch", "Early dinner"],
    brandTone: "Warm, simple, neighborhood-focused",
    postingPreferences: { cadencePreference: "Up to 3 posts/week when usable media is available", preferredDays: ["Tuesday", "Friday"], toneNotes: "Clear and friendly", contentBoundaries: ["No unconfirmed offers"], communicationPreference: "Weekly check-in" },
    mediaSupplyStatus: "usable",
    platformAccessStatus: "ready_for_review",
    businessTruthStatus: "ready_for_team_review",
    firstWeekSetupStatus: "needs_team_setup",
    proofInputStatus: "partial",
    overallStatus: "first_week_setup_needed",
    nextClientAction: "Confirm holiday hours if they will be mentioned.",
    nextTeamAction: "Review Google/Maps presence and prepare first picture-based content plan.",
    blockers: [],
    warnings: ["Holiday hours are not confirmed."],
    readySignals: ["Core links are present", "Usable launch media batch is available", "Best sellers are identified"],
    mediaAvailable: ["food photos", "best seller photos", "storefront photo", "menu photo/link"],
    businessTruth: baseTruth,
    proofInputs: { mainCustomerType: "Families and lunch regulars", mostWantedAction: "orders", currentWeakPoints: ["Inconsistent photo freshness"], orderLinkAvailable: true, menuLinkAvailable: true, googleConfidence: "Needs review", socialConfidence: "Basic", trackingSignalsAvailableLater: true },
    updatedAt: "2026-06-04T00:00:00.000Z",
  },
  {
    clientId: "complete-presence-low-media-benchmark",
    restaurantName: "Complete Online Presence low-media benchmark",
    packageId: "complete_online_presence",
    contactName: "Manager contact",
    contactRole: "Manager",
    phone: "(555) 010-2000",
    email: "complete-presence-media@example.com",
    address: "200 Preview Way, Sample City, ST",
    websiteUrl: "https://example.com/complete-presence-low-media",
    googleBusinessProfileUrl: "",
    googleMapsUrl: "https://maps.google.com/example-complete-presence-low-media",
    instagramUrl: "https://instagram.com/example_complete_presence_media",
    facebookUrl: "",
    tiktokUrl: "",
    menuUrl: "https://example.com/complete-presence-low-media/menu",
    orderingUrl: "",
    reservationUrl: "",
    cateringUrl: "",
    cuisineType: "Quick-service bowls",
    bestSellers: ["Chicken bowl"],
    foodCategories: ["Bowls"],
    customerTypes: ["Lunch customers"],
    busyDays: ["Wednesday"],
    busyTimes: ["Lunch"],
    brandTone: "Fresh and direct",
    postingPreferences: { cadencePreference: "Simple rhythm once photos are available", preferredDays: [], toneNotes: "Short captions", contentBoundaries: ["No price claims without confirmation"], communicationPreference: "Text reminders" },
    mediaSupplyStatus: "low",
    platformAccessStatus: "links_needed",
    businessTruthStatus: "confirmation_needed",
    firstWeekSetupStatus: "blocked",
    proofInputStatus: "client_inputs_needed",
    overallStatus: "media_needed",
    nextClientAction: "Send 5–10 clear food photos of best-selling items and confirm the Google Business Profile link if available.",
    nextTeamAction: "Request best seller photos and confirm missing Facebook/order links before first-week content prep.",
    blockers: ["Usable media batch is not ready"],
    warnings: ["Google Business Profile link is missing", "Facebook link is missing", "Order link is missing"],
    readySignals: ["Menu link is available", "Primary contact is available"],
    mediaAvailable: ["menu photo/link"],
    businessTruth: { ...baseTruth, hoursConfirmed: false, orderingReservationLinksConfirmed: false },
    proofInputs: { mostWantedAction: "visits", currentWeakPoints: ["Not enough current food photos", "Order link unclear"], orderLinkAvailable: false, menuLinkAvailable: true, trackingSignalsAvailableLater: false },
    updatedAt: "2026-06-04T00:00:00.000Z",
  },
  {
    clientId: "complete-presence-media-ready-benchmark",
    restaurantName: "Launch media-ready benchmark",
    packageId: "complete_online_presence",
    contactName: "Operating contact",
    contactRole: "Operator",
    phone: "(555) 010-3000",
    email: "complete-presence-ready@example.com",
    address: "300 Preview Way, Sample City, ST",
    websiteUrl: "https://example.com/complete-presence-ready",
    googleBusinessProfileUrl: "https://business.google.com/example-complete-presence-ready",
    googleMapsUrl: "https://maps.google.com/example-complete-presence-ready",
    instagramUrl: "https://instagram.com/example_launch_ready",
    facebookUrl: "https://facebook.com/example-complete-presence-ready",
    tiktokUrl: "https://tiktok.com/@example_launch_ready",
    menuUrl: "https://example.com/complete-presence-ready/menu",
    orderingUrl: "https://example.com/complete-presence-ready/order",
    reservationUrl: "https://example.com/complete-presence-ready/reserve",
    cateringUrl: "https://example.com/complete-presence-ready/catering",
    cuisineType: "Modern casual dining",
    bestSellers: ["Chef plate", "Loaded fries", "House dessert"],
    foodCategories: ["Entrees", "Appetizers", "Desserts"],
    customerTypes: ["Dinner groups", "Weekend visitors"],
    busyDays: ["Friday", "Saturday", "Sunday"],
    busyTimes: ["Dinner"],
    brandTone: "Polished, visual, welcoming",
    postingPreferences: { cadencePreference: "Strong weekly rhythm with reels support", preferredDays: ["Monday", "Thursday"], toneNotes: "Calm but not formal", contentBoundaries: ["Confirm any dietary claims"], communicationPreference: "Weekly progress update" },
    mediaSupplyStatus: "strong",
    platformAccessStatus: "ready_for_review",
    businessTruthStatus: "confirmed",
    firstWeekSetupStatus: "ready",
    proofInputStatus: "ready_for_internal_review",
    overallStatus: "ready_for_manual_service",
    nextClientAction: "No urgent client input needed for preview setup.",
    nextTeamAction: "Prepare first-week manual execution plan and first client-safe update.",
    blockers: [],
    warnings: [],
    readySignals: ["Strong photo batch", "Short video readiness", "launch platform links present", "Business details confirmed"],
    mediaAvailable: ["food photos", "best seller photos", "fresh best-seller photos", "storefront photo", "menu photo/link", "dining room optional"],
    businessTruth: { ...baseTruth, holidayHoursConfirmed: true, cateringAvailabilityConfirmed: true, orderingReservationLinksConfirmed: true },
    proofInputs: { averageTicket: "Client may provide later", currentMonthlyCustomerGoal: "Client may provide later", mainCustomerType: "Dinner groups", mostWantedAction: "orders", currentWeakPoints: ["Needs stronger weekly consistency"], orderLinkAvailable: true, menuLinkAvailable: true, googleConfidence: "Moderate", socialConfidence: "Strong media, inconsistent rhythm", ownerReportedBaselineNotes: "Owner wants clearer weekly feedback.", trackingSignalsAvailableLater: true },
    updatedAt: "2026-06-04T00:00:00.000Z",
  },
  {
    clientId: "launch-incomplete-links-benchmark",
    restaurantName: "Launch incomplete-links benchmark",
    packageId: "complete_online_presence",
    contactName: "Partner contact",
    contactRole: "Partner",
    phone: "(555) 010-4000",
    email: "complete-presence-links@example.com",
    address: "400 Preview Way, Sample City, ST",
    websiteUrl: "",
    googleBusinessProfileUrl: "https://business.google.com/example-complete-presence-links",
    googleMapsUrl: "",
    instagramUrl: "https://instagram.com/example_launch_links",
    facebookUrl: "https://facebook.com/example-complete-presence-links",
    tiktokUrl: "",
    menuUrl: "",
    orderingUrl: "https://example.com/complete-presence-links/order",
    reservationUrl: "",
    cateringUrl: "",
    cuisineType: "Bakery cafe",
    bestSellers: ["Breakfast sandwich", "Iced coffee"],
    foodCategories: ["Breakfast", "Coffee", "Pastries"],
    customerTypes: ["Morning commuters", "Weekend brunch"],
    busyDays: ["Saturday"],
    busyTimes: ["Morning"],
    brandTone: "Bright and local",
    postingPreferences: { cadencePreference: "Future video notes only; Reels/TikTok coming soon", preferredDays: ["Wednesday"], toneNotes: "Light and clear", contentBoundaries: ["No unconfirmed seasonal items"], communicationPreference: "Weekly email" },
    mediaSupplyStatus: "inconsistent",
    platformAccessStatus: "links_needed",
    businessTruthStatus: "confirmation_needed",
    firstWeekSetupStatus: "blocked",
    proofInputStatus: "partial",
    overallStatus: "platform_links_needed",
    nextClientAction: "Confirm website/menu/Google Maps/TikTok links if available and send one fresh fresh best-seller photo.",
    nextTeamAction: "Ask client to confirm missing menu and Google Maps links before preparing the Complete Online Presence picture-based path.",
    blockers: ["Menu link missing", "Google Maps link missing"],
    warnings: ["TikTok is coming soon and not required at launch", "Media supply has been inconsistent"],
    readySignals: ["Facebook and Instagram links are present", "Best sellers are listed"],
    mediaAvailable: ["food photos", "storefront photo"],
    businessTruth: { ...baseTruth, menuItemsConfirmed: false, orderingReservationLinksConfirmed: false },
    proofInputs: { mainCustomerType: "Morning commuters", mostWantedAction: "visits", currentWeakPoints: ["Missing public links", "Inconsistent uploads"], orderLinkAvailable: true, menuLinkAvailable: false, googleConfidence: "Unknown", socialConfidence: "Needs consistency", trackingSignalsAvailableLater: true },
    updatedAt: "2026-06-04T00:00:00.000Z",
  },
  {
    clientId: "complete-presence-advanced-benchmark",
    restaurantName: "Advanced readiness benchmark",
    packageId: "complete_online_presence",
    contactName: "Founder contact",
    contactRole: "Founder",
    phone: "(555) 010-5000",
    email: "complete-presence-advanced@example.com",
    address: "500 Preview Way, Sample City, ST",
    websiteUrl: "https://example.com/complete-presence-advanced",
    googleBusinessProfileUrl: "https://business.google.com/example-complete-presence-advanced",
    googleMapsUrl: "https://maps.google.com/example-complete-presence-advanced",
    instagramUrl: "https://instagram.com/example_complete_presence_advanced",
    facebookUrl: "https://facebook.com/example-complete-presence-advanced",
    tiktokUrl: "https://tiktok.com/@example_complete_presence_advanced",
    menuUrl: "https://example.com/complete-presence-advanced/menu",
    orderingUrl: "https://example.com/complete-presence-advanced/order",
    reservationUrl: "https://example.com/complete-presence-advanced/reserve",
    cateringUrl: "https://example.com/complete-presence-advanced/catering",
    cuisineType: "Full-service restaurant",
    bestSellers: ["Grilled entree", "Signature appetizer", "Catering tray"],
    foodCategories: ["Dinner", "Catering", "Desserts"],
    customerTypes: ["Families", "Event planners", "Dinner guests"],
    busyDays: ["Thursday", "Friday", "Saturday"],
    busyTimes: ["Dinner"],
    brandTone: "Calm, confident",
    postingPreferences: { cadencePreference: "Complete Online Presence weekly update rhythm", preferredDays: ["Tuesday", "Friday"], toneNotes: "Refined and warm", contentBoundaries: ["Confirm claims and ad details before public use"], communicationPreference: "Weekly review plus monthly report" },
    mediaSupplyStatus: "strong",
    platformAccessStatus: "ready_for_review",
    businessTruthStatus: "confirmation_needed",
    firstWeekSetupStatus: "needs_team_setup",
    proofInputStatus: "ready_for_internal_review",
    overallStatus: "business_truth_needed",
    nextClientAction: "Confirm any catering details and business-truth changes before Veroxa prepares public-facing copy.",
    nextTeamAction: "Keep future ads/video planning parked and focus current onboarding on Complete Online Presence readiness.",
    blockers: ["future ads/video readiness deferred", "ads are coming soon and not included at launch"],
    warnings: ["Catering availability needs final confirmation before being used publicly"],
    readySignals: ["Strong media batch", "launch platform links present", "Proof inputs are ready for internal review"],
    mediaAvailable: ["food photos", "best seller photos", "fresh best-seller photos", "storefront photo", "menu photo/link", "customer-safe ambience optional", "catering/large order optional"],
    businessTruth: { ...baseTruth, holidayHoursConfirmed: true, cateringAvailabilityConfirmed: false, futureAdsAcknowledged: false, futureReadinessAssessmentAcknowledged: false },
    proofInputs: { averageTicket: "Client may provide later", currentMonthlyCustomerGoal: "Client may provide later", mainCustomerType: "Families and event planners", mostWantedAction: "catering", currentWeakPoints: ["Needs careful proof setup", "future ads planning remains coming soon"], orderLinkAvailable: true, menuLinkAvailable: true, googleConfidence: "Moderate", socialConfidence: "Strong", ownerReportedBaselineNotes: "Owner wants better visibility into what online actions matter.", trackingSignalsAvailableLater: true },
    updatedAt: "2026-06-04T00:00:00.000Z",
  },
];

export function getRestaurantOnboardingSeedProfiles(): RestaurantOnboardingProfile[] {
  return restaurantOnboardingSeedProfiles;
}

export function getClientOnboardingPreviewProfile(): RestaurantOnboardingProfile {
  return restaurantOnboardingSeedProfiles[1];
}
