/**
 * visibilityAuditRepository — read-only accessors over the demo audits.
 *
 * Runs the rule engine across the demo fixture inputs once and exposes the
 * computed audits plus the prepared-action seeds they generate. Pure and
 * offline: NO network, NO storage, NO external execution. The store imports
 * `getVisibilityAuditPreparedActionSeeds()` so audit findings flow into the same
 * Approval Queue as the hand-written prepared actions.
 */

import { demoVisibilityAuditInputs } from "@/data/demo/demoVisibilityAudits";
import { getRestaurantName } from "@/data/demo/demoClients";
import {
  generatePreparedActionsFromVisibilityAudit,
  runVisibilityAudit,
  type VisibilityAudit,
  type VisibilityAuditResult,
} from "@/domain/visibilityAudit";
import type { ResolvedPreparedActionSeed } from "@/domain/preparedActions";

/** Audits computed once from the fixtures (deterministic, so caching is safe). */
const audits: VisibilityAudit[] = demoVisibilityAuditInputs.map((input) => ({
  id: `audit-${input.clientId}`,
  input,
  result: runVisibilityAudit(input, { restaurantName: getRestaurantName(input.clientId) }),
}));

export function getAllVisibilityAudits(): VisibilityAudit[] {
  return audits;
}

export function getVisibilityAuditResults(): VisibilityAuditResult[] {
  return audits.map((a) => a.result);
}

export function getVisibilityAuditForClient(clientId: string): VisibilityAudit | undefined {
  return audits.find((a) => a.input.clientId === clientId);
}

/** All prepared-action seeds generated by the demo audits, for the store. */
export function getVisibilityAuditPreparedActionSeeds(): ResolvedPreparedActionSeed[] {
  return audits.flatMap((a) => generatePreparedActionsFromVisibilityAudit(a.result));
}

export interface VisibilityAuditOverview {
  auditedCount: number;
  totalFindings: number;
  highPriorityFindings: number;
  preparedActionCount: number;
  averageScore: number;
}

/** A small roll-up across all audits for the dashboard card. */
export function getVisibilityAuditOverview(): VisibilityAuditOverview {
  const results = getVisibilityAuditResults();
  const totalFindings = results.reduce((n, r) => n + r.findings.length, 0);
  const highPriorityFindings = results.reduce(
    (n, r) => n + r.findings.filter((f) => f.severity === "high" || f.severity === "urgent").length,
    0,
  );
  const preparedActionCount = results.reduce((n, r) => n + r.preparedActionCount, 0);
  const averageScore = results.length
    ? Math.round(results.reduce((n, r) => n + r.overallScore, 0) / results.length)
    : 0;
  return {
    auditedCount: results.length,
    totalFindings,
    highPriorityFindings,
    preparedActionCount,
    averageScore,
  };
}
