export type MomoAiDraftGenerationStatus = "disabled_by_default" | "blocked" | "needs_business_truth_confirmation" | "needs_media_rights_confirmation" | "needs_brand_rule_review" | "eligible_for_internal_draft_only" | "team_review_required" | "future_step_required";
export type MomoAiDraftGenerationRisk = "low" | "medium" | "high" | "critical";
export type MomoAiDraftGenerationCategory = "Generation Gate" | "Required Inputs" | "Business Truth Dependencies" | "Media Rights Dependencies" | "Brand Voice Dependencies" | "Prompt Assembly Rules" | "Blocked Claims" | "Allowed Draft Types" | "Output Safety Labels" | "Team Review Workflow" | "Disabled / Failure States" | "Future Enablement Requirements" | "Safe Internal Next Decision";
export type MomoAiDraftGenerationRuleItem = { id: string; category: MomoAiDraftGenerationCategory; title: string; status: MomoAiDraftGenerationStatus; risk: MomoAiDraftGenerationRisk; description: string; allowed_behavior: string; blocked_behavior: string; required_confirmation: string; safe_internal_next_step: string; route_href?: string };
export const MOMO_AI_DRAFT_GENERATION_FEATURE_FLAG = "VITE_VEROXA_MOMO_AI_DRAFT_GENERATION_ENABLED";
export const MOMO_AI_DRAFT_GENERATION_CATEGORIES: MomoAiDraftGenerationCategory[] = ["Generation Gate", "Required Inputs", "Business Truth Dependencies", "Media Rights Dependencies", "Brand Voice Dependencies", "Prompt Assembly Rules", "Blocked Claims", "Allowed Draft Types", "Output Safety Labels", "Team Review Workflow", "Disabled / Failure States", "Future Enablement Requirements", "Safe Internal Next Decision"];
const item = (id: string, category: MomoAiDraftGenerationCategory, title: string, status: MomoAiDraftGenerationStatus, risk: MomoAiDraftGenerationRisk, description: string, allowed_behavior: string, blocked_behavior: string, required_confirmation: string, safe_internal_next_step: string, route_href?: string): MomoAiDraftGenerationRuleItem => ({ id, category, title, status, risk, description, allowed_behavior, blocked_behavior, required_confirmation, safe_internal_next_step, route_href });
export const MOMO_AI_DRAFT_ALLOWED_TYPES = ["Instagram caption draft", "Facebook caption draft", "Google update draft", "short-form video caption idea", "content idea list", "weekly content suggestion", "simple local SEO copy idea"] as const;
export const MOMO_AI_DRAFT_OUTPUT_SAFETY_LABELS = ["internal_draft_only", "team_review_required", "business_truth_check_required", "media_rights_check_required", "sensitive_claim_check_required", "blocked_for_public_use", "not_customer_visible", "not_published"] as const;
export const MOMO_AI_DRAFT_REVIEW_STATES = ["generated_internal_draft", "needs_team_review", "needs_faraz_review", "needs_owner_confirmation", "approved_for_manual_execution", "rejected_or_held"] as const;
export const MOMO_AI_DRAFT_GENERATION_RULE_ITEMS: MomoAiDraftGenerationRuleItem[] = [
item("gate-disabled", "Generation Gate", "Disabled until every safety gate is satisfied", "disabled_by_default", "critical", "AI generation is disabled by default unless AUTH_MODE is real, the authenticated user is Team role, the explicit feature flag is enabled, confirmed business truth exists, permissioned media rules are satisfied when media is referenced, brand voice/prompt rules have been reviewed, Team review workflow is available, and no customer-visible action is triggered.", "Hold an internal architecture checklist for future Team-only generation.", "Do not generate from route load, placeholder mode, missing flag, missing truth, missing media permission, missing brand review, or any customer-visible action path.", "Faraz approval, real auth approval, Team role, feature flag, confirmed business truth, media-rights confirmation when relevant, and brand-rule review are required.", "Keep the foundation disabled and review the blockers.", "/team/control-center"),
item("inputs-required", "Required Inputs", "Future request input contract", "blocked", "high", "A future request must include content goal, content pillar, confirmed business-truth facts, media reference only if usage rights are confirmed, blocked claims list, brand voice rules, draft type, intended internal reviewer, and no publication destination.", "Define request shape only.", "Do not accept open-ended prompts, unconfirmed facts, or publication destinations.", "Team must confirm each input before future generation is even eligible.", "Review business truth, media, and brand pages before any later implementation.", "/team/momo-business-truth"),
item("truth-dependencies", "Business Truth Dependencies", "Confirmed facts only", "needs_business_truth_confirmation", "critical", "AI drafts must not reference menu items, prices, hours, address, phone, order links, delivery, catering, halal/dietary/sensitive claims, awards, rankings, popularity, or platform status unless confirmed through the business-truth review path.", "Use only confirmed business facts in later internal drafts.", "Do not invent facts, offers, sensitive claims, awards, platform access, or availability.", "Owner/client confirmation is required for business-truth changes before public/customer-visible use.", "Review AI generation blockers against the business-truth pack.", "/team/momo-business-truth"),
item("media-dependencies", "Media Rights Dependencies", "Permissioned media only", "needs_media_rights_confirmation", "critical", "AI drafts may reference media only if media exists, is not fake/generated, usage rights are confirmed, staff/customer consent is confirmed if faces appear, dish availability is confirmed, media is not misleading, and Team review is required.", "Reference permissioned media rules later when safe.", "Do not upload, create, seed, generate, fake, or imply media rights automatically.", "Media usage rights require owner confirmation before public use.", "Review media inventory blockers before any future draft request.", "/team/momo-media-content"),
item("brand-dependencies", "Brand Voice Dependencies", "PR #117 voice constraints", "needs_brand_rule_review", "high", "Future drafts must be warm, simple, crave-focused, local, approachable, first-timer friendly, and food-forward while avoiding corporate tone, fake urgency/scarcity, unconfirmed claims, fake discounts, fake reviews, fake popularity, and overpromising.", "Use approved brand voice rules as constraints.", "Do not produce hype, claims, fake reviews, or overpromising language.", "Brand voice and AI prompt rules must be reviewed by Team/Faraz.", "Review the PR #117 rulebook before any later generation work.", "/team/momo-brand-ai-rules"),
item("prompt-assembly", "Prompt Assembly Rules", "Safe prompt assembly guidance", "future_step_required", "medium", "A future server-only prompt should include system intent, restaurant context, confirmed facts only, allowed content pillar, blocked claims, media-use status, output format, Team-review label, and no-publication reminder.", "Document server-side-only prompt assembly boundaries.", "Do not add frontend provider calls, public keys, executable provider calls, or route-load generation.", "Server-side provider decision and prompt safety review are required later.", "Keep prompt guidance static until a separate approved implementation PR."),
item("blocked-claims", "Blocked Claims", "Claims blocked unless explicitly confirmed", "blocked", "critical", "Blocked claims include best/top-rated/number one, guaranteed growth, customer count, sales/revenue/order claims, health claims, halal/dietary claims unless confirmed, ownership/family-owned unless confirmed, authentic/origin unless confirmed, fake testimonials/reviews, fake ranking/popularity, fake urgency/scarcity, fake promotions/offers, and unconfirmed availability.", "Maintain a blocked-claims list for future safety checks.", "Do not allow blocked claims into generated or reviewed output.", "Sensitive claims are blocked until owner-confirmed.", "Use this list as a future preflight blocker."),
...MOMO_AI_DRAFT_ALLOWED_TYPES.map((draftType) => item(`allowed-${draftType.toLowerCase().replaceAll(" ", "-")}`, "Allowed Draft Types", draftType, "eligible_for_internal_draft_only", "medium", `${draftType} is allowed only as a later internal-only draft type.`, "Keep internal-only and Team-review required.", "Do not publish, expose to client, or treat as approved.", "Team/Faraz review is required before customer-visible use.", "Select first draft types only in a later approved PR.")),
item("labels", "Output Safety Labels", "Required labels for future AI output", "team_review_required", "high", `Future output must be labeled ${MOMO_AI_DRAFT_OUTPUT_SAFETY_LABELS.join(", ")}.`, "Require safety labels on any future internal output.", "Do not create unlabeled, customer-visible, published, or auto-approved output.", "Business truth, media rights, sensitive claim, and Team review checks are required.", "Use labels as review gates later."),
item("workflow", "Team Review Workflow", "Review states before manual execution", "team_review_required", "high", `A future draft must move through ${MOMO_AI_DRAFT_REVIEW_STATES.join(", ")} with risky items requiring Faraz review and business-truth/media/sensitive issues requiring owner confirmation.`, "Model review states only.", "Do not implement live publishing, client-visible approval, owner approval flow, or automatic approval.", "Separate Team/Faraz review is required before any manual execution.", "Keep workflow as internal planning until approved."),
item("failure-states", "Disabled / Failure States", "Honest blocked states", "disabled_by_default", "critical", "Failure states include AI generation disabled by default, placeholder auth mode, missing feature flag, missing confirmed business truth, missing media rights, sensitive claims blocked, brand rules incomplete, no external platform destination configured by design, and no publish action available.", "Show honest disabled status.", "Do not present readiness, launch, external destination, or publish capability.", "Every failure state requires explicit later resolution.", "Keep disabled state visible on the Team page."),
item("future-enable", "Future Enablement Requirements", "Separate approval required", "future_step_required", "critical", "Before real generation can be enabled later, Faraz must explicitly approve, real auth must be approved, a server-side AI provider decision and secure server-side secret handling must exist, prompt safety must be reviewed, business truth and media rights must be confirmed, Team review workflow must be validated, and no public/customer-visible auto-action may exist.", "List future requirements.", "Do not enable generation, secrets, background work, publishing, or external sync in this PR.", "Separate explicit Faraz approval is required.", "Defer enablement to a future approved PR."),
item("safe-next", "Safe Internal Next Decision", "Review the rules; take no external action", "future_step_required", "medium", "Faraz reviews controlled generation rules, Team confirms which draft types should be first, generation stays disabled until the next approved PR, no external action occurs from this PR, and no next activation PR is approved by default.", "Use this as the only next decision.", "Do not activate, contact, publish, or unlock owner walkthrough.", "Faraz must explicitly approve any future real-world activation.", "Review this foundation internally.")
];
export const MOMO_AI_DRAFT_ALLOWED_TEAM_LINKS = ["/team/momo-brand-ai-rules", "/team/momo-media-content", "/team/momo-business-truth", "/team/momo-pilot-prep", "/team/momo-live-readiness", "/team/momo-activation-gate", "/team/control-center", "/team/profile-corrections", "/team/upload-inbox", "/team/messages", "/team/activity-log", "/team/ai-drafts", "/team/reports-from-activity"];
export const isMomoAiDraftGenerationFeatureEnabled = () => import.meta.env.VITE_VEROXA_MOMO_AI_DRAFT_GENERATION_ENABLED === "true";
